apps/twitterfollows/twitter_follows.star

This commit updates schema to the new schema version.

twitter-follows: Updated schema.

---

apps/bigclock/big_clock.star

Port of implementation from [go-sunrise][1]. Uses pure math so there's
no need to call out to an external API.
[1]: https://github.com/nathan-osman/go-sunrise

bigclock: Calculate sunrise/sunset in Starlark

---

apps/apps.go
apps/daynightmap/day_night_map.star
apps/daynightmap/daynightmap.go

This app displays a world map with the night portion shaded in.  It can optionally also show the time and/or the date.

Added Day & Night World Map app

---

apps/apps.go
apps/pokedex/pokedex.go
apps/pokedex/pokedex.star

This PR introduces the Pokedex app to the community repo! The app was created with the `make app` command and the code was copied from [`mackorone/tidbyt-pokedex`](https://github.com/mackorone/tidbyt-pokedex). The app gets data from [PokeAPI](https://pokeapi.co/), which it then displays as a static image.

Add Pokedex app

---

apps/pokedex/pokedex.star

The pokeapi requests that we cache so we don't incur high fees on their part: https://pokeapi.co/docs/v2. This change adds caching and error checking when calling to their API. We will now cache pokemon and their assets for 7 days.
- pokedex: Add caching and error handling.
- This commit adds caching and error handling around fetching pokemon. We will now cache a pokemon for 7 days to go easy on their API.

pokedex: Add caching and error handling.

---

apps/apps.go
apps/sbbtimetable/sbb_timetable.star
apps/sbbtimetable/sbbtimetable.go

This app generates a real-time timetable for any train station in the Swiss Public Transportation Network. It shows the departure time and destination of the next five trains that are leaving the chosen station. If a train is delayed, this delay is also shown.
The station can be set with the _station_ parameter. Additionally, with the parameter _skiptime_, it is possible to show departures in the future. As an example: If this parameter is set to _10_ Minutes, the departures between _now_ and _now+10 minutes_ are skipped and the next five departures departing after _now+10 minutes_ are shown.

Add SBB app

---

apps/apps.go
apps/datetimeclock/date_time_clock.star
apps/datetimeclock/datetimeclock.go

Thanks for all the help doing this betterengineering!

Added clock2

---

apps/nightscout/nightscout.star

This commit refactors nightscout slightly to be able to support sample
data. This is important so we can render previews in the app store.

nightscout: Add preview data.

---

apps/bigclock/big_clock.star
apps/clockbyhenry/clock_by_henry.star
apps/daynightmap/day_night_map.star
go.mod
go.sum

In the latest Pixlet, `config.get` always returns a string. We instead
need to use `config.bool` to get boolean values.

Replace config.get with config.bool

---

apps/daynightmap/day_night_map.star

I used a higher quality encoding of the map as the color reduction artifacts were bothering me.
I added the ability to center the map horizontally on the longitude of the location.

day_night_map: Used truecolor map image and added centering feature.

---

apps/apps.go
apps/phaseofmoon/phase_of_moon.star

This can sometimes get out of sync if folks are not using the `make
apps` command or if merge conflicts are resolved through the UI. This
commit cleans up this file.

bugfix: Fix app manifest.

---

apps/apps.go
apps/mbta/mbta.go
apps/mbta/mbta.star

Add MBTA transit app

---

apps/apps.go
apps/dateprogress/date_progress.star
apps/dateprogress/dateprogress.go

A visualization of daily/monthly and yearly progress, inspired by the [@year_progress twitter bot](https://twitter.com/year_progress)

Add Date progress app

---

apps/apps.go
apps/steam/steam.go
apps/steam/steam.star

This app displays what a user is currently playing on Steam, along with the art for the game.  If the user is currently not playing a game, the list of games from the previous two weeks of activity is displayed.
The users' profile must be public in order to display the game activity.

Steam App for Tidbyt

---

apps/apps.go
apps/binaryclock/binary_clock.star
apps/binaryclock/binaryclock.go

This PR provides a binary clock app.
The colors of the dots, the color of the background of the dots as well as the color of the text can be changed. Further it is possible to set the width and height of the bars.
It is also possible to hide the text to create a binary clock over the whole display.

Binary clock

---

apps/clockbyhenry/clock_by_henry.star

This is just printing a lot to Tidbyt server logs.

clockbyhenry: Remove print statement

---

apps/sportsstandings/sports_standings.star

Forgot an input when calling `frame_vec` with cached data.

Fixed minor call to function `frame_vec`

---

apps/apps.go
apps/nearearthobjs/near_earth_objs.star
apps/nearearthobjs/nearearthobjs.go

This app hits the Near Earth Object API [NeoWs](https://www.neowsapp.com/) to display the name of the next nearest object to Earth as well as the relative time, distance, and speed of when it will miss.
Also allows the user to configure kilometers vs miles.

Adding Near Earth Objects App

---

apps/googletraffic/google_traffic.star

- Coordinates are now used to query the API from google.
- Introduced a new config field, which hides the country from the addresses shown on the TidByt

Google: Switch to coordinates and new config

---

README.md

This commit updates the badges so they are consistent and provide links
to our social channels.

docs: Update badges.

---

apps/espnnews/espn_news.star

Fix isn't pretty, but it works. 
Preview should now work correctly in Tidbyt App and each sport is cached separately as well.

Fixed cache issues in ESPN news app

---

apps/pagerduty/pagerduty.star

This PR adds mock data when the auth token is not present. 
Preview:
I'm happy to replace my client ID and secret with ones owned by Tidbyt if provided.

pagerduty: Add Mock data for preview

---

apps/analogtime/analog_time.star
apps/analogtime/analogtime.go
apps/apps.go

Apparently my app name can't have a number in it...
Anyways because we needed more clocks here's another analog clock created using `render.Plot`
There is a toggle to display the date in the top left corner (default is to disable)

Add Analog Time app (Attempt two)

---

apps/apps.go
apps/fishbyt/fishbyt.go
apps/fishbyt/fishbyt.star

The fish facts app that everybody needed but nobody wanted (unless you are David Winitch, in which case you wanted this app as well) is finally here. This is my first time doing a pull request so hopefully everything checks out
.

Adding the Fishbyt app

---

apps/espnnews/espn_news.star

Added Features:
- There is a speed option to slow down the scroll text (slowing down may not allow text to finish, but there's nothing that can be done with that at the moment)
- There is an option to scroll the text vertically now as well.

ESPN News: Added two feature requests

---

apps/sportsstandings/sports_standings.star

Added a dropdown to display only a single conference/league
Added a speed option in an attempt to allow for more time for standings to display.

Sports Standings: Added two requested schema features.

---

apps/noaabuoy/noaa_buoy.star
apps/noaabuoy/noaabuoy.go

This commit fixes the config IDs so the app takes parameters as
expected. In addition, it updates the description to include the URL
since the field descriptions are not currently used in the app.

noaa-buoy: Fix config IDs.

---

apps/googletraffic/google_traffic.star

Added the following changes:
- An alias for the destination and the origin can be provided. In that case, the alias is shown instead of the address
- The Distance is shown in a fourth row instead of the same row as the time
- The units of the time are shown in their short representation (eg. m instead of min)
- The Distance can now be shown in miles and kilometers

Google Traffic App: Updates

---

apps/nycbus/nyc_bus.star

This commit adds preview data so that we can render the app without
having to make an authenticated request.

nycbus: Fix issue with previews.

---

apps/analogtime/analog_time.star

timezone from config was not getting obtained properly. The changes here should fix that

Analog Time: Fixed error in config for getting location timezone

---

apps/apps.go
apps/verticalmessage/vertical_message.star
apps/verticalmessage/verticalmessage.go

This was a quick feature request on the community and I think this actually belongs more so as a feature addition to the messages app, but since I don't have the original source code, I created a simple app to display a long vertical message.
The user can also select a few colors and change the scroll speed.
Feel free to reject the PR or use the code to modify the existing messages app though.

Add Vertical Message App

---

.devcontainer/devcontainer.json

This commit sets the color to be solarized to match the devtools panel. cc @drudge

devcontainer: Set color to solarized.

---

apps/nft/nft.star

We can't decrypt it for some reason and it's breaking an upstream test.

nft: Remove broken secret

---

apps/nft/nft.star

encrypted opensea api key using the correct app name "nft"

fix secret using nft as app

---

apps/apps.go
apps/weathermap/weather_map.star
apps/weathermap/weathermap.go

This app displays real-time precipitation radar for a location.
It uses the API provided for free by RainViewer: https://www.rainviewer.com/api.html
Configuration options include:
* Choose the zoom level, which is expressed in kilometers / miles.
* Choose from a selection of 8 different color schemes.
* Show a time overlay in either 12-hour or 24-hour format, or turn it off.
* Show a coverage overlay using kilometers / miles, or turn it off.
* Enable or disable the "snow" layer.

Add 'Weather Map' app.

---

apps/noaabuoy/noaa_buoy.star

pulls a list of nearby buoys using the locationbased schema field.  I was unable to completely test this in the dev environment but I know the get_stations function does work when passed in a valid location object with lat,lng
The list of buoys is pulled in as rss from https://www.ndbc.noaa.gov/rss/ndbc_obs_search.php?lat=21.417&lon=-157.680

NOAA Buoy : Location based buoy list

---

apps/path-train-schedule/path_train_schedule.star

Displays the arrival times for trains coming into each PATH station.

path train schedule

---

apps/weathermap/weather_map.star

Fix typo in 'Weather Map' app.

---

apps/pokedex/pokedex.star

Also adds a space between number and units.
ptal @mackorone

Add option to pokedex to show imperial units.

---

apps/nft/nft.star

Uses another Opensea API to fetch the NFT's collection stats and display the floor price.  Add some error checking for fake collections/NFTs out there.

Adds a configurable floor price to the display

---

apps/apps.go
apps/warframecycles/warframe_cycles.star
apps/warframecycles/warframecycles.go

This very simple app displays the time remaining in the current cycles for the open world areas in the free-to-play game [Warframe](https://www.warframe.com/). I use my Tidbyt next to my computer, and figuring out which time in which cycle at a glance is really nice. Of course, [Warframe Hub](https://hub.warframestat.us/#/) does a nice job of this, but if I don't want to dedicate a whole browser tab to it, Tidbyt is great. I'm still relatively new to Python, and very new to Starlark, having just gotten my Tidbyt last week, so if the code looks amateurish, it is! Any suggestions are welcome.

Creating a Warframe Cycles app

---

apps/worldclock/world_clock.star

This (hopefully) resolves the issue identified by @drudge on [Discord](https://discord.com/channels/928484660785336380/928485908842426389/948685887569547285). I'm not sure how to test it out myself.
Also this pull request replaces #221, which was causing merge conflicts.

World clock bug fix

---

apps/pagerduty/pagerduty.star

This PR is to address feedback raised in #239.
* Increases the result set size to 100, up from the default of 25.
* Adds filtering by the profile ID if the user only cares about their own on-call status.
* Iterates through all `oncalls` result sets returned by the filter, rather than only returning the first.
* Optimizes caching to reduce storing unused properties.

pagerduty: Handle more than 25 on-call shifts

---

apps/spotthestation/spotthestation.star

non-unique cache key meant all users shared the same location

spotthestation : use cache unique to location url

---

apps/dateprogress/date_progress.star

@possan I've updated your app to utilize color functions that can dynamically adjust the color rather than hard coding the colors (as I suggested in https://github.com/tidbyt/community/issues/41, it would be sweet if there was a global color library that could be used for this purpose).
Anyway, this PR gives users the ability to choose colors for each of the progress bars for a bit more personalization. I haven't been able to test it with the schema, but I'm _pretty_ sure I got it all right.

Updating Date Progress app to use color functions and added color schema

---

apps/powerball/powerball.go
apps/powerball/powerball.star

Tidbyt team welcome to another adventure of Amillion Air tries to learn how to do coding things. I have bought a second tidbyt for my parents and i know they love to play the Powerball so i figured id make this simple app for them to keep them up to date!
App shows
Current Prize Pool
Last numbers drawn
Last draw date and if there were any winners
next draw date

Add PowerBall

---

apps/destiny2stats/README.md

Cleaned up readme and added some extra information

Destiny 2 Stats - Updated Readme

---

apps/apps.go
apps/happyhour/happy_hour.star
apps/happyhour/happyhour.go

Hello again! I'm back with a new app. This one is called Happy Hour. It uses the [CocktailDB's](https://www.thecocktaildb.com/) free random drink generator API. It displays a drink image, name, and the list of ingredients, and the cache refreshes at the top of the hour so everyone enjoys the same cocktail.
In this image everything fits on the page, but if the ingredients are too long, they scroll vertically. If the drink name is too long, it scrolls horizontally.

New App: Happy Hour

---

apps/destiny2stats/destiny_2_stats.star

Adjusted logic for most recent character function to make it cleaner, extended the cache time, added in some default values as secret values so the app displays something when no values are provided, regenerated api key secret value.

Destiny 2 stats: Clean-up

---

apps/destiny2stats/destiny_2_stats.go

Fixed summary as there was an issue from when I had initially generated the file.

Destiny 2 Stats: Updated go file

---

apps/sportsscores/sports_scores.star

Added NBA scores. Due to size restrictions here NBA scores have two games per frame so can put status on two lines (otherwise text may overlap, this ensures it never should)
While testing NBA with pixlet serve found an MLB bug and the status stuff was all weird. This PR SHOULD fix this, but the app may error with MLB on there without it, so wanted to at least provide a patch so the app did not break.
Will be serving it on my tidbyt to continue checking

Sports Scores: Added NBA and fixed MLB bug

---

apps/spotthestation/spotthestation.star

This fixes a small bug in the current version. The XML from NASA doesn't contain timezone information, so I need to know the users timezone to know when a sighting has occurred, so I know when to display the next sighting. 
I also give the option of not showing this application by passing back [] when there are no known future sightings.

Location needed for knowing timezone, hide when no sightings upcoming.

---

apps/apps.go
apps/surflive/surflive.go
apps/surflive/surflive.star

This app fetches live surf conditions for a surf spot provided by the user.
Because of the limited real estate and the amount of info surfers want, this app focuses on the swell and wind conditions:
- Most significant swell height (or surf height), direction and period
- Wind direction and speed
Future options could include support for other units (meter for height, and kph, mph for wind speed)

Add Surflive app

---

README.md
docs/FAQ.md

This commit adds an FAQ to answer questions about the linter and the
release process.

docs: Add FAQ.

---

apps/flags/README.md
apps/flags/flags.star

- Adds option to display the country name
- Adds option to set country name color
- Adds option to set background color

Flags: New Options!

---

apps/flags/flags.star

- Replaces our pseudo random number generator with the new official random number module.

Flags: switch to new random number module

---

apps/apps.go
apps/goodservice/goodservice.star

This commit resolves issues with the linter and the build.

bugifx: Fix linter and build.

---

apps/apps.go
apps/natdex/natdex.go

This commit adds the app to the list of apps and fixes the summary so
that the tests will pass.

bugfix: Fixup natdex.

---

apps/sportsstandings/sports_standings.star
apps/sportsstandings/sportsstandings.go

Noticed standings may have been slightly behind, since data is only grabbed once a day, so grabbing three times a day instead

Sports Standings: Grab data three times a day instead of once (added team highlight feature too)

---

apps/nationaltoday/nationaltoday.go
apps/nationaltoday/nationaltoday.star

Added code to account for words longer than 64 pixels

National Today: Account for words longer than 64 pixels

---

apps/vergetaglines/verge_taglines.star

This update to the Verge Taglines app does two things:
- Add retrieving the header image and placing it behind the Verge logo
- Add fallback values for text and image to ensure app doesn't die in the event of a CSS change on theverge.com
There are some header images which end up either rather bland (mostly black, for example) or overwhelmingly colorful (which ends up making the Verge logo not as clear). In the former case, the Verge logo maintains a strong presence as it did in the initial version. In the latter, the logo is less noticeable in favor of the awesome art. In most cases, they'll combine to look really cool, as seen in the examples attached.
Local dev renders using recent headers/images

Update(Verge Taglines): Add background image and resilience

---

apps/analogtime/analog_time.star
apps/analogtime/analogtime.go

User can now customize the colors of the analog time clock

Analog Time: Add Custom color options

---

apps/apps.go
apps/charlestownferry/README.md
apps/charlestownferry/charlestownferry.go
apps/charlestownferry/charlestownferry.star

Displays the next three departure times for the Charlestown, MA ferry. No more having to open the mTicket app and painfully navigate to the ferry schedule to see when the next ferry will be!

New App: Charlestown Ferry Departures

---

apps/apps.go
apps/climateclock/climate_clock.star
apps/climateclock/climateclock.go

This is a relatively simple, yet impactful app. We display two screens here relating to climate change:
- **The Deadline**: a countdown to the estimated point where a 1.5°C increase in global temperatures will be irreversible
- **The Lifeline**: the percent of the world's energy generated by renewable sources (wind, solar, hydro etc.)
NYC locals may recognize the first as the countdown that has displayed in Union Square above the Best Buy since 2020. Last year, similar clocks were also installed in Glasgow and Seoul. The origin story of this clock is related to Greta Thurnberg's UN speech and is intended to spread awareness about the urgency of climate change. Tidbyt owners who decide to display one or both of these clocks will have a chance to start a conversation with the people around …

New App: Climate Clock

---

apps/apps.go

This commit adds formula one to the apps list so we can see it in our
repo.

formula-one: Fix apps list.

---

apps/dailykanji/dailykanji.star

This commit sets our own API key for the daily kanji app.

dailykanji: Fix API key.

---

apps/warframecycles/warframe_cycles.star

Fixed a time display bug, and added the new open area with placeholder text and a toggle to enable it.

Warframe Cycles: Fixes plus add new feature

---

apps/worldclock/world_clock.star

World Time: Added option for meridian time

---

apps/verticalmessage/vertical_message.star

User can now adjust line spacing of vertical message

Vertical Message: Add line spacing option

---

apps/goodservice/goodservice.star

This commit fixes a config option for direction. cc @blahblahblah-

goodservice: Fix direction issue.

---

apps/ifparank/ifparank.star

This commit updates the API key to use one that Tidbyt has access to.

ifparank: Set Tidbyt api key.

---

apps/warframecycles/warframe_cycles.star

There were still some instances where I was ending up with weird displays. Removing these two conditionals fixes it.

fix last display issue

---

apps/mlbleaders/mlb_leaders.star

Text now starts at the bottom or far right of screen

MLB Leaders: Adjust Marquee offsets

---

apps/fivesomewhere/five_somewhere.star

Per a suggestion by Boba Fett's Ship on the discord, add in location awareness and an animation to let you know you made it, you hard-working person you.

Five somewhere location awareness

---

apps/sportsscores/sports_scores.star

To be consistent with NHL the period is now at the end and time is always in the first row with the scores

Sports Scores: NBA status order

---

apps/goodservice/goodservice.go
apps/goodservice/goodservice.star

Update goodservice app's manifest and fix schema formatting, and more abbreviations for destination display.

goodservice: Update manifest and formatting fixes

---

apps/sportsstandings/sports_standings.star

Adds NFL to the option of standings. Also removes the fail statement and returns an error message if data can't be obtained

Sports Standings: Add NFL and remove `fail`

---

apps/sportsscores/sports_scores.star

Will need to verify this works in real time when the season starts, but this adds NFL to the sports scores

Sports Scores: Add NFL

---

apps/fullybinarytime/fullybinarytime.star

This seems a better idea than hardcoding 13 numbers. Doesn't affect display.

Simplify computing digits

---

apps/goodservice/goodservice.star

Follow-up to #435, fixes a missing space.

goodservice: Fix missing space for station name

---

apps/mlbleaders/mlb_leaders.star

User can now have random stats shown each time

MLB Leaders: Added random statistic feature

---

apps/sportsscores/sports_scores.star

games can now be scrolled vertically if desired instead of only paginated

Sports Scores: Add scroll feature

---

apps/apps.go
apps/subreddit/README.md
apps/subreddit/subreddit.go
apps/subreddit/subreddit.star

Displays the #&#x2060;1 post of a given subreddit. Also displays the current time in a given timezone in either 24-hour or 12-hour format.

New App: Subreddit

---

apps/redditrplace/reddit_r_place.star

Place image I used was too big so the pixel sizes were too big 😕

Reddit R-Place: Fix bug with pixel size.

---

apps/apps.go
apps/ogsgamesviewer/ogs_games_viewer.star
apps/ogsgamesviewer/ogsgamesviewer.go

I am an avid go player (the Chinese abstract strategy game) and wanted to make an app that would artfully display a selection of my in-progress games. This app uses an OGS ([online go server](https://online-go.com)) Username to pull in-progress go games from the OGS API and display them, along with the name of the opponent and what color they're playing.
If there are improvements to the app, I'd be happy to make them! Please let me know if there's anything you need me to change. Thank you and I hope my app can be added!
EDIT: Updated the .gif preview using the new code

Added the OGS Games Viewer App

---

apps/subreddit/subreddit.star

Adds JSON decoding of location config that was missing.
Should fix subreddit app that is currently not displaying on community.

subreddit: fix parsing of location config

---

apps/apps.go
apps/metar/metar.go
apps/metar/metar.star

This is a new app that is capable of displaying airport METARs and derived flight category summaries: VFR (visual flight rules), IFR (instrument flight rules), MVFR (marginal VFR), etc.
It supports displaying the raw METAR text for a single airport, or scalable summary displays showing flight category for 2-15 airports.
The user enters a list of airport ICAO codes as a comma-separated text config.

New app: METAR (aviation weather)

---

apps/sfnextmuni/sf_next_muni.star

Despite fixing the sets issue in pull request #469, the LocationBased schema still doesn't appear to be working: https://discuss.tidbyt.com/t/setting-up-sf-next-muni/2839.

SF Next Muni: Set a default location instead of a default stop, to verify that at least get_stops() is working correctly

---

apps/pokedex/pokedex.star

Swapped the random function with the new `random.number` module available in pixlet. Not sure if this will help with the app constantly repeating a lot of the starter pokemon in the evening (at least in my experience).
However this should ideally be tested before actually making it live. I also only commented out the original random module stuff just in case that wasn't the issue. FWIW locally it seems to randomize, but doesn't always on the tidbyt it seems.
cc @mackorone as they are the original author and there may be something else different that I'm missing?

Pokedex: Swap Random function

---

apps/redditrplace/README.md
apps/redditrplace/reddit_r_place.star

Changing `animation.AnimatedPositioned` (**deprecated**) to `animation.Transform` - also re-work the animation and gave the schema for some options on how far the image can scroll...

Update animation component

---

apps/sportsscores/sports_scores.star

can now display game times using local timezone, games still switch over w.r.t to eastern timezone though

Sports Scores: Display game times in local timezone

---

apps/pagerduty/pagerduty.star

This PR fixes https://github.com/tidbyt/community/issues/452 by restricting the incident list returned to only teams the user is on.
It also adds the ability to restrict the applet view to a single team's stats only.

pagerduty: Filter incidents by user's team, allow limiting to specific team

---

apps/apps.go
apps/stockticker/stock_ticker.star
apps/stockticker/stockticker.go

A simple stock ticker app.  Add three stock symbols, and an API key for Alpha vantages - and you have a stock ticker.  5 min cache for stock data.

StockTicker

---

apps/shuffleimages/shuffle_images.star

Previously didn't implement displaying images in order, now the images will display in order with a new one every 60 seconds
edit: a `sequence` counter would be useful here :)

Shuffle Images: Implemented ordinal display of images

---

apps/nationaltoday/nationaltoday.star

Added the option to just display a QR code to the website with the holidays for today

NationalToday: Add QR code

---

apps/apps.go
apps/severewxalertsusa/severewxalertsusa.go
apps/severewxalertsusa/severewxalertsusa.star

Display severe weather alerts issued by the US National Weather Service.

Severe WX Alerts USA

---

apps/severewxalertsusa/severewxalertsusa.star

This commit cleans up the lat/lng truncation to ensure it's being
truncated properly.

severewxalertsusa: Address location truncation.

---

apps/londonbusstop/london_bus_stop.star
apps/tube/tube.star

Both of these apps disappointingly failed to work for real on my actual Tidbyt. When trying to configure them on my phone, the location look up doesn't actually provide a list of stops/stations to choose from.
See descriptions on each of the commits for details of why I think this should work. I'd appreciate a second eye. I'm not honestly 100% confident in the fixes, given that I thought they were going to work before. It's a difficult dev workflow when you have to wait for the actual release to be able to test it, and it's not obvious how the handlers wrap intermediate outputs.

Fix London apps

---

apps/sportsscores/sports_scores.star

Added some college sports, basically should be pulling from teams in top 25 for college sports
Also added EPL for soccer
Fixed a potential bug in highlighting winners in NHL games
Rearranged the schema since can only have one generated field, etc.

Sports Scores: Add sports and other adjustments

---

apps/isitchristmas/is_it_christmas.star

Christmas is only 25 December in certain parts of the world.
This extends @austinrfnd 's app to support the other possible dates to be more inclusive.

That would be an ecumenical matter

---

apps/fairfaxconnector/fairfax_connector.star

Due to the way that the BusTime API was returning a lack of predicted arrivals as an error and not just as an empty list, whenever it gets late at night and there are no buses, the app would show "API Error". This handles that behavior as well as displaying a little picture of a bus stop when there are no scheduled arrivals.

Better handling of no bus arrivals [Fairfax Connector]

---

apps/sportsscores/sports_scores.star

time_format and local tz was not working because it was only being set when data was initially obtained and saved under the same cache key. Now the time is formatted in get_frames

Sports Scores: Fix time options

---

apps/shuffleimages/shuffle_images.star

Added image delay so the delay of the image can be set if a gif is defined

Shuffle Images: Add image delay

---

apps/randomcats/random_cats.star
apps/randomcats/randomcats.go

- cache gif and nongif data separately
- add cataas.com credit to manifest

randomcats: minor tweaks for release

---

apps/apps.go
apps/blackout/blackout.go
apps/blackout/blackout.star
apps/howoldami/howoldami.go
apps/howoldami/howoldami.star

Black out TidByt during evenings (or whenever)

Add Blackout & How Old Am I?

---

apps/noaatides/noaa_tides.star

Add support AM/PM display of time.  Also improve layout with H or L indicators and time aligned left with tide heights aligned right.

Nooa tides layout update

---

apps/apps.go
apps/roblox/README.md
apps/roblox/roblox.go
apps/roblox/roblox.star

Displays an online friends or favorite games view for a specified Roblox username.
A pulsating green dot will appear if the Roblox user is online, otherwise it will show gray for offline. Friend avatars also provide an online vs offline dot indicator.
This app provides various UI options. The user can customize their experience by choosing to show their online friends vs. favorite games views, selecting an accent text color or enabling dark vs. light modes.  
These customizations can be adjusted using the properties of the app.

Add Roblox app

---

apps/shopifychart/shopify_chart.star

Also fixed an error that could cause an index out of bounds error

Added screen if there are no orders

---

apps/noaatides/noaa_tides.star

Add pretty graph of tide data.  Add auto sizing of station name based on length.  Add more fault tolerant code when pulling data from tides api.

add graphing and station name display

---

apps/busytube/busy_tube.star
apps/shabbat/shabbat.star

[pixlet v0.18.3](https://github.com/tidbyt/pixlet/releases/tag/v0.18.3) provides a library function for day of week, so I don't need to implement it myself.

Simplify day of week calculation

---

apps/nascarnextrace/nascarnextrace.go

added embed command and fixed description text

updated go file for NASCAR app

---

apps/severewxalertsusa/severewxalertsusa.star

@aschechter88  I added a toggle so if set to true then the app only shows up when there is a weather alert. 
This DOES NOT remedy #646. Although now that I look at it, I think I MAY know the issue there, but I will respond within the issue itself.

SevereWxAlertsUSA: Add option to show app only when there are alerts.

---

apps/fitbitweight/fitbitweight.star

Fixed a number of issues. Changed how the plotting was done, as what was checked in was no longer working, although I swear it was when I checked it in. 
Also, handle no data, handle little data, handle old data.
Addressed some documentation errors as well. 
Removed unused references.

Fix plotting issue

---

apps/apps.go
apps/nesquotes/README.md
apps/nesquotes/nes_quotes.star
apps/nesquotes/nesquotes.go

This PR adds a TidByt Applet to display randomized quotes from Nintendo Entertainment System games, alongside animated game sprites.

Added NES Quotes App

---

apps/goodservice/goodservice.star

Small fix in logic for this rare occasion. Also added more abbreviations to train destinations.

Goodservice: Fix logic for when next train is due, and the following train is delayed

---

apps/officestatus/office_status.star

This PR contains a couple of minor changes to fix bugs in the office status applet.

fix: Bug fixes for office status applet

---

apps/noaatides/noaa_tides.star

add ylim config and use config.bool for graph pref
add graph scaling option.
fix 12pm/am bug, set default graph minimum to 0

noaatides : add graph scaling option

---

apps/officestatus/office_status.star

The oAuth token refresh workflow was broken. This app only currently works until the first access token expires. These commits fix that issue.

fix: oAuth token refresh workflow fixes

---

apps/apps.go
apps/xtrabyt/xtrabyt.go
apps/xtrabyt/xtrabyt.star

This app provides integration with Xtrabyt.
Xtrabyt is a platform built to provide a way for users to create custom drawings for their Tidbyt. Plans exist to further expand the offerings of Xtrabyt to include integrations with other online services to display other information and data.
Thanks for considering my contribution.
Here is the default screen:

New App: Xtrabyt

---

apps/datetimeclock/date_time_clock.star

updated @AmillionAirs  app to add option to display date in US format vs Intl format.

DateClockTime: added US date format to options

---

apps/sfnextmuni/sf_next_muni.star

This fixes predictions, partially addressing #804. I haven't fixed announcement messages yet, I still have to work out where in the 511.org API they are served.

Update SF Next Muni to use the 511.org API

---

apps/sfnextmuni/sf_next_muni.star
apps/sportsscores/sports_scores.star

Had a small bug when getting the date in the basketball function, this PR fixes that so the app should work correctly now.
When I ran `make lint` it also modified the `sf_muni` app too for some reason. Just FYI.

Sports Scores: Fix Basketball bug

---

apps/switchboard/switchboard.star

This is a minor change to the way that the Switchboard api token is handled to improve the security of the tokens in transit.

Switchboard App Update: Improve Token Security w/ Basic Auth

---

apps/apps.go
apps/todaysname/todays_name.star
apps/todaysname/todaysname.go

A small app that shows this days name that celebrate "Nameday" in Sweden

Add new app - showing today's name in Sweden

---

apps/noaabuoy/noaa_buoy.star

increase cache time for main data in case of extended api failures

noaa_buoy_cache_update_2 : use cache during spurious api failures

---

apps/daystoxmas/days_to_xmas.star

* Use `ceil` instead of `floor` for number of days remaining, since this seems to be more natural to how humans count "days".
* On the actual day of, display "0 days left", rather than 365 days left to the next Christmas.

daystoxmas: Fix number of days remaining

---

apps/vergetaglines/verge_taglines.star

The Verge updated their site today and appear to be using hydration to render certain content only once it's loaded into a DOM. Since the HTTP module does not do anything beyond loading the raw text-based response body, I've had to update the logic here to parse out the tagline fro the underlying JSON blob.
This is just to fix the app because currently it displays a blank face in production.
I'm targeting a script tag with an embedded JSON blob used for hydration and then iteratively checking the presence of the path I expect in that JSON lob since there doesn't appear to be a try-except/catch method supported in Starlark.

Update verge taglines to work with non-hydrated home page

---

apps/aadailyreflect/aadailyreflect.star

- moved start of scroll down a little more to get the title 
- fixed issue with html quot chars being in text
- changed scroll - some reflections are really long, with 75 - better chance of seeing it until other timing options available

fix: aadailyrefelection - speed and html chars

---

Makefile
apps/apps.go

- [feat: Add sync to Makefile.](https://github.com/tidbyt/community/commit/8cf8aa2e00c1f873b5ae25cfef8ed49243067e8b) 
- This commit adds the sync command to the makefile to make it easier to use.
- [bug: Fix Positive Quote.](https://github.com/tidbyt/community/commit/1d02bf84604d9bb603a1777887494c916b72437b) 
- This commit adds positive quote to the apps list so it can be discoved in our backend.

bug: Fix Postive Quote.

---

apps/shopifymemories/shopify_memories.star
apps/shopifyneworder/shopify_new_order.star
apps/shopifyneworder/shopifyneworder.go

- fix animations in new orders and memories apps
- description update for shopify new order app

Fix animations in shopify new order and memories

---

apps/earthquakemap/README.md
apps/earthquakemap/earthquake_map.star

Found a bug in the use of the location-based settings. The bug is fixed along with some other code refactoring for cleanliness. Also, forgot to run the linter before the PR. Fixed.

earthquakemap: v0.1.1 fixes location bug and linter error

---

apps/trambyt/trambyt.star

Only some stops have departures, handle that better.
Also properly widens badge to fit longer line identifiers.

[trambyt] Handle stops without departures

---

apps/apps.go
apps/hubblelive/README.md
apps/hubblelive/hubble_live.star
apps/hubblelive/hubblelive.go

Presents the current observation status of the Hubble Space Telescope as provided by the [Space Telescope Science Institute](https://www.stsci.edu/) website, [Space Telescope Live](https://spacetelescopelive.org/).

Hubble Live: v0.1.0 - New App

---

apps/nightscout/nightscout.star

This PR adds bars to the vertical axis at the beginning of every hour. The hour bars are subtle, but they add a lot of context at a glance!

feat(nightscout): Add vertical axis bars every hour

---

apps/aadailyreflect/aadailyreflect.star

fixed new format on web page without bolded text.
added cleanup for html chars
fixed error handler not returning a list

fix: AADailyReflect -  new format on web page & error handling

---

apps/isitchristmas/is_it_christmas.star

My Swedish friends open their presents on Julafton on the 24th, so that's when they'd want to count down until.

Add 24 December option

---

apps/apps.go
apps/fido/fido.go
apps/fido/fido.star

I really love the idea of having a little companion with you - I have a dog of my own and he's my best friend. I decided that some of us might not have the physical pal, but would love a pixel pal.
Fido is the pixel Pal for your Tidbyt. Give them a name, and give them a Birthday and watch them grow with you!
I want to add more environments as well as include new and exciting options for a pal (cats, and exotics some day). I hope that you all find it as fun as I do to have a digital friend with you throughout the day!
My goal was to also include a "activity meter" but its not entirely possible without a backend to support it or variables that can be stored on device. One day we will have the abilities and then we can update Fido accordingly!

New App: Fido

---

apps/anyprogressbar/any_progressbar.star
apps/anyprogressbar/anyprogressbar.go
apps/apps.go

Displays one or more progress bars.
The idea is to install one or more instances and use Tidbyt API to update the configuration to show statuses.
This is a new take on #590 that depends on config instead of arbitrary URLs.

New App: Any Progressbar for Tidbyt

---

apps/anyprogressbar/any_progressbar.star
apps/ctaltracker/cta_l_tracker.star
apps/dailyreminder/daily_reminder.star
apps/soccertables/soccer_tables.star

I am working through resolving linter issues through `pixlet lint -r --fix ./` and manual fixes so we can enable the linter on every change.

More resolvable linter issues.

---

apps/launchcountdown/launchcountdown.star
apps/noaabuoy/noaa_buoy.star
apps/noaatides/noaa_tides.star
apps/pathtrainschedule/path_train_schedule.star
apps/soundtransit/sound_transit.star
apps/warframecycles/warframe_cycles.star

This commit resolves the outstanding issues for the "unreachable" linter by removing or reorganizing code that is unreachable.

Remove unreachable code.

---

apps/fantasynamegen/fantasynamegen.star
apps/ncaafscores/ncaaf_scores.star
apps/ncaafstandings/ncaaf_standings.star
apps/ncaamscores/ncaam_scores.star
apps/nflscores/nfl_scores.star
apps/nflstandings/nfl_standings.star
apps/nhllive/nhl_live.star

This commit resolves more unused variable linter warnings. This change is part of a larger effort to enable `pixlet lint` for PRs on this repo.

More unused variable fixes.

---

apps/eplscores/eplscores.star
apps/martamap/marta_map.star
apps/mlbleaders/mlb_leaders.star
apps/mlbscores/mlb_scores.star
apps/mlbstandings/mlb_standings.star
apps/mlsscores/mls_scores.star
apps/nbascores/nba_scores.star
apps/nbastandings/nba_standings.star

This commit resolves additional linter warnings for unused variables. This is part of a larger change to be able to enable `pixlet lint` on PRs for the community repo.

Fix unused variables.

---

apps/abstractclock/abstract_clock.star

This commit sets max age for abstract clock.

fix abstract clock.

---

apps/apps.go
apps/newapps/new_apps.star
apps/newapps/newapps.go

List new tidbyt apps within the last week.
Display is very similar to that of the NationalToday app.

New App: New Apps

---

apps/nightscout/nightscout.star

add max_age=120 to three instances of render.Root()

Nightscout: Add Max Age

---

apps/soccermens/soccermens.star
apps/soccerwomens/soccerwomens.star

fixed soccer apps - not using time color setting, updated
also removed un-needed code

Fix: Mens & Women's Soccer timecolor

---

apps/bblcricket/bbl_cricket.star
apps/bored/bored.star
apps/discordmembers/discordmembers.star
apps/githubactivity/github_activity.star
apps/hassentity/hass_entity.star
apps/lastfm/last_fm.star
apps/ncaamstandings/ncaam_standings.star
apps/newapps/new_apps.star
apps/njtransit/nj_transit.star
apps/opmstatus/opm_status.star
apps/pgatour/pga_tour.star
apps/skireport/ski_report.star
apps/soccermens/soccermens.star
apps/soccerwomens/soccerwomens.star
apps/solaredgemonitor/solaredge_monitor.star
apps/stockvalue/stock_value.star
apps/stripesales/stripe_sales.star

This commit resolves newly added linter errors. This change allows us to enable `pixlet check -r` on the repo which will ensure all apps are valid. In the near future, apps will be required to pass pixlet check before they are able to be merged.

lint: Resolve newly added linter errors.

---

go.mod
go.sum

This commit bumps the pixlet version for community.

fix: Bump pixlet version.

---

apps/bblcricket/bbl_cricket.star

Batting team info fields in the API no longer exists, and now pulling info from another part
Also noted that rain delay message not displaying for team batting second.

fix: BBL Cricket

---

apps/bored/README.md
apps/bored/bored.star

- Added Customized messages, and percentage chance of showing them
- Defaults to local messages if they exist, if AP is down.

Feature Updates: The Bored App, Version 2.00001

---

apps/desknametag/desk_name_tag.star

This PR includes two new dropdowns for users to select custom colors. Additionally, I've updated a few app field names to make what users put on the additional lines of the name tag less opinionated.

App Update: Color selectors and minor changes for Desk Name Tag

---

apps/ambientweather/ambient_weather.star

This is an update to the Ambient Weather app.
1. Handles weather stations without UV or wind sensors and with multiple temperature and humidity sensors.
2. Ability to choose which temperature sensor: Inside, Sensor 1, or Sensor 2.
3. Ability to choose which humidity sensor: Inside, Sensor 1, or Sensor 2.
closes #990

Ambient Weather Updates

---

apps/mathclock/manifest.yaml
apps/mathclock/math_clock.star

Here's another clock. This one displays the hour and minute as a math equation.
The equations are created using the same code (converted to Starlark here obviously) found in this repo that created an [arduino clock](https://github.com/ElliotTheGreek/ArduinoMathClock).
Example with a delayed time visible:

New App: Math Clock

---

apps/tidbytclocks/manifest.yaml
apps/tidbytclocks/tidbyt_clocks.star

Lists the clocks available on the Tidbyt!!!
Honestly the list was less than I thought it may be... 
But this should make @AmillionAirs happy. 
Edit: forgot the gif
Edit2: updated gif with correct preview

New App: Tidbyt Clocks

---

apps/onthisday/manifest.yaml
apps/onthisday/onthisday.star

New app that displays events in history from today's date. Uses open API https://byabbe.se/on-this-day for loading data

new app - on this day events

---

apps/nightscout/nightscout.star

Align large clock display to align with other clock apps

Nightscout: Align clock to match other apps

---

apps/sa20cricket/manifest.yaml
apps/sa20cricket/sa20_cricket.star

Similar to my BBL Cricket app, this app is for the South African T20 tournament

New App: SA20 Cricket

---

apps/ilt20cricket/ilt20_cricket.star
apps/ilt20cricket/manifest.yaml

Similar to my BBL Cricket app, this app is for the International League T20 tournament

New App: ILT20 Cricket

---

apps/fullybinarytime/fullybinarytime.star
apps/fullybinarytime/manifest.yaml

Update description so it is included in the clock app app

---

go.mod
go.sum

Renovate's bump #1074 failed to update go.sum(?)

bump pixlet

---

apps/aadailyreflect/aadailyreflect.star
apps/countupclock/countupclock.star
apps/nascarnextrace/nascarnextrace.star
apps/theguardiannews/theguardiannews.star

AA Daily Reflection
The Guardian News
NASCAR Next Race
CountUp Clock

add:  show full animation to affected apps

---

apps/babyage/baby_age.star
apps/babyage/manifest.yaml
apps/babyage/readme.md

Initial Baby Age App, simple app to show a baby's age in days/weeks/months

Initial Create of Baby Age App

---

apps/adelaidemetro/adelaide_metro.star

Some services were showing times for different services at that stop. I just needed to clear out some variables before the rendering happened

Bug fix: Adelaide Metro

---

apps/netflixtop10/manifest.yaml
apps/netflixtop10/netflix_top_10.star

This shows the Top 10 movies or films on Netflix for the current week. The data comes from the TSV files listed at the bottom of [top10.netflix.com](https://top10.netflix.com/).
Users can select the category (TV or Film) and region (Global, or by country), as well as configure the scroll direction and font size. Several renders in different configurations:
<p>
</p>

New app: Netflix Top 10

---

apps/soccermens/README.md
apps/soccermens/soccermens.star
apps/soccerwomens/README.md
apps/soccerwomens/soccerwomens.star

add option to display home team first or away team first (@jesushairdo provided feature)
removed multi-instance need
added option to control display speed between 1.0 and 3.0 seconds (5 options in total)

feat: Soccer Men's and Women's

---

apps/jokesjokeapi/jokes_jokeapi.star
apps/mathclock/math_clock.star
apps/mlbleaders/mlb_leaders.star
apps/nationaltoday/nationaltoday.star
apps/newapps/new_apps.star
apps/sportsscores/sports_scores.star
apps/sportsstandings/sports_standings.star
apps/tidbytclocks/tidbyt_clocks.star
apps/tvquotes/tv_quotes.star
apps/verticalmessage/vertical_message.star

Added show_full_animation and max_age to appropriate apps

Add show_full_animation and max_age to appropriate apps

---

apps/womenst20wc/womens_t20_wc.star

The app was too quick to move on to the next upcoming match, so I made some changes that will show the most recent match result for 24hrs before moving on
Also noted that standings were not appearing correctly. Found that Cricinfo decided to change the Group Names from A & B to 1 & 2 .... changed code to match

Update: Womens T20 WC

---

apps/pslcricket/manifest.yaml
apps/pslcricket/psl_cricket.star

Yes, its another T20 cricket app
I just noticed that the Pakistan Super League starts Feb 13 so why not do an app for it? 
Too much cricket is never enough!

New App: PSL T20 Cricket

---

apps/acnhvillager/acnhvillager.star
apps/acnhvillager/manifest.yaml

Hi everyone! First-time contributor here--I've decided to leverage  `acnhapi.com` to display a random villager from Animal Crossing: New Horizons including their in-game icon, personality, species, and catch-phrase with colors matching each character! Includes Schema options for translated names and catchphrases in different locales. 
I went through some pretty thorough dev testing for API errors and name/species/catch-phrase lengths to ensure proper padding and alignment are achieved in any case. The error image is the green leaf furniture icon from Animal Crossing.
The villager's name should be center-aligned (or my best approximation) and the information on the right should be right-aligned--this is done by inserting spaces into the strings. It appears it's not possible to leverage …

New App: AC:NH Villager

---

apps/pgatour/pga_tour.star

Added rotation speed options and slight formatting change to tournament title

Update: PGA Tour

---

apps/whosthatpokemon/whosthatpokemon.star

I want to see people guess "Is it Quagsire?" and then say "what the hell is that????" when it's actually Clodsire. To that end, I have updated the pokemon number to be accurate to the final pokemon of the latest generation.

Who's That Pokemon update

---

apps/soccerwomens/README.md
apps/soccerwomens/soccerwomens.star

added SheBelieves Cup to Women's Soccer

Feat: Soccer Women's - added SheBelieves Cup

---

apps/canvas/canvas.star
apps/canvas/manifest.yaml

This app allows users to connect their Tidbyt to Canvas so they can view their upcoming assignments.  I have tried to do my best at following the instructions on your website but if I have messed something please let me know and I will fix it.

Add Canvas App

---

apps/actransit/ac_transit.star
apps/actransit/manifest.yaml

AC Transit shows bus departures times for a stop chosen by the user, taking inspiration from many other transit projects in the repo.

Create AC Transit App

---

apps/nsbyt/nsbyt.star

Fixed a bug that returns "no running trains" if no skip time was set by the user. Also caching is improved.

Fix: NS Timetable

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Fix sample data mmol delta display
Version to 2.2.5

Nightscout: Fix sample data mmol delta display

---

apps/solarmanagerch/manifest.yaml
apps/solarmanagerch/solar_manager_ch.star

Include the instructions for obtaining api key and site id in the main app description not just in hidden schema fields.

solar_manager_ch : update description to include api key instructions

---

apps/severewxalertsusa/severewxalertsusa.star

Add the show_full_animation flag to show all alerts
cc @aschechter88 for visibility.

SevereWxAlertsUsa: Show full animation

---

apps/kielferry/kiel_ferry.star

- Update REST api URL
- Update REST query
- Update error handling; render HTTP status code

KielFerry now using V6 of underlying REST api

---

apps/whosthatpokemon/whosthatpokemon.star

When I increased the pokemon to 1008, I realized that I broke the API limit of the service I use to make them into silhouettes which has a max limit of 1000 images. I don't have time at this exact moment to resolve this, so for now, so it works, I just sliced off the last 8 pokemon. Sorry  Wo-Chien, Chein-Pao, Ting-Lu, Chi-Yu, Roaring Moon, Iron Valiant, Koraidon, and Miraidon.

Who's that Pokemon - Lessening the Pokemon Slightly

---

apps/whosthatpokemon/whosthatpokemon.star

Addresses https://github.com/tidbyt/community/issues/1232 by converting the int to a string for the print statement

fix(whosthatpokemon): Stringify status code

---

apps/chicagotribune/README.md
apps/chicagotribune/chicago_tribune.star
apps/chicagotribune/manifest.yaml

Hi, I've created an app that pulls stories from the [Chicago Tribune's RSS Feed](https://www.chicagotribune.com/about/ct-chicago-tribune-rss-feeds-20220922-jub4o6cwwza4xd3d7ybqi7qz3i-htmlstory.html) and displays either the latest headlines or the latest article.
Here are some screenshots of the app.
Please let me know if you have any questions. Thank You!

Chicago Tribune RSS Feed

---

apps/3cellularautomata/3cellularautomata.star
apps/amazing/amazing.star
apps/cellularautomata/cellularautomata.star
apps/life/life.star

It's much nicer than only offering 12 colours in a drop down.
Question: is it OK to change the type of existing fields? Worried that you have values saved in your DB that won't be compatible with the updated schema. I _think_ it should be OK here if the old values were a hex string, and the new values are too. But would appreciate confirmation.

Use new colour picker

---

apps/aadailyreflect/aadailyreflect.star

update to bypass a recurring issue with the web content formatting

fix : AA Daily Reflection

---

apps/mtatraintime/mtatraintime.star

This fixes a timezone issue I noticed after the app was merged earlier.

mtatraintime: Fix timezone

---

apps/analogtime/analog_time.star
apps/jokesjokeapi/jokes_jokeapi.star
apps/verticalmessage/vertical_message.star

also changed the fail code message in jokesapi while I was here, nothing else changed in it though

Add Color Picker: Swap color picker out in appropriate apps

---

apps/ipl/ipl.star
apps/ipl/manifest.yaml

New T20 app that shows scores for the Indian Premier League, starting April 1
Similar to my other T20 cricket apps with a couple more new details
- Shows what's happened over the last 12 balls
- Shows what the team batting second need to win and off how many balls

New App: IPL Cricket

---

apps/teslasolar/tesla_solar.star

This commit fixes:
1. Caching issue
2. Display issue when only on solar power
3. Improved error handling. Errors will now display on TidByt.

Bug fixes and improved error handling

---

apps/pollencount/pollen_count.star

The api required an api key and then there were other bugs fixed.
cc @N-Brooks for visibility and to make sure things were done correctly. I may have forgotten to take something out.

Pollen Count: Added authorization and fixed bugs so it doesn't break.

---

apps/costcalculator/cost_calculator.star
apps/costcalculator/manifest.yaml

Per a request on the discourse channel. This app shows the elapsed time and calculates a cost given a specified rate. It only shows hours and minutes. Would be great if there was a toggle on the datetime to only have to choose the time and not date and time.

New App: Cost Calculator

---

apps/gitlabissues/gitlab_issues.star
apps/gitlabissues/manifest.yaml

Shows the amount of newly added issues since last displayed on tidbyt for a user. If no new ones were added, show the total amount of open issues.

New App: Gitlab Issues

---

apps/trimetarrivals/README.md
apps/trimetarrivals/manifest.yaml
apps/trimetarrivals/trimet_arrivals.star

Simple app to display next arrival at a given bus stop.
I have read the CLA Document and I hereby sign the CLA

TriMet Arrivals app

---

apps/tessie/tessie.star

Update Tessie colors for low Tesla battery states

Update Tessie colors

---

apps/unixepochclock/manifest.yaml
apps/unixepochclock/unix_epoch_clock.star

Show a simple clock with seconds since the Unix epoch.

Add Unix Epoch Clock

---

apps/company_clock/company_clock.star
apps/company_clock/manifest.yaml

Displays a rendition of the clock from the game "Lethal Company".

New App: Lethal Company Clock

---

apps/la_metro/la_metro.star
apps/la_metro/manifest.yaml

This app lookups arrival predictions for la metro rail near a location. It requires the user to enter their own API key, as the official LA Metro API (swiftly) requires authentication and places limits on API usage.

New App: Los Angeles Metro Rail arrivals

---

apps/aflscores/afl_scores.star

Reduced cache to 6hrs to retrieve the round number quicker
Needed to convert draws to string value for team records

Update & fix: AFL Scores

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Several users have reached out about issues experienced with the latest changes. Paul and I have been working on more gracefully falling back to previous api calls if v2 does not work, or does not have all of the required data to display.

Emergency Bug Fixes!

---

apps/underwaterclock/underwater_clock.star

Fish have been added! Some of the scenes have also been slightly changed, plus an option to show or hide the fish.

Update to Underwater Clock

---

apps/nightscout/README.md
apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Corrected a minor bug where the "+" was not showing on the delta for some users
Corrected a bug where users with NS display set to mmol were not rendering
Cleaned up some variable names and comments
Updated description fields
Updated README with more current information and for readability
Reduced number of BG readings in v1 API code to 200 from 1000
Changed display units to Dropdown from Toggle
Added ability to create a colored outline to ID multiple instances for multiple T1D's in a household

Nightscout: Updated Features and Bug Fixes

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Box spacing to fix broken layout caused by colored border in last version

Nightscout: Urgent Bug Fix

---

apps/nolayingup/no_laying_up.star

Updated to reflect change in titles in RSS feed

Update: No Laying Up

---

apps/fuzzyclock/fuzzy_clock.star

Fuzzy Clock: adding de-DE-alt3 to address Berlin area

---

apps/nextufc/manifest.yaml
apps/nextufc/next_ufc.star

Submitting a new app that shows the next upcoming UFC event.

New App: Next UFC

---

apps/nrlscores/nrl_scores.star

Made draw in W-D-L records dynamic

Update: NRL Scores

---

apps/producthunt/README.md
apps/producthunt/manifest.yaml
apps/producthunt/product_hunt.star

This app shows the daily top tech products being launched on [Product Hunt](https://www.producthunt.com/).
There is an option to show only the current top product, or the top 3 where each one is displayed for about 5 seconds.

New app: Product Hunt top products

---

apps/northernlights/manifest.yaml
apps/northernlights/northern_lights.star

This is initialization of the Northern Lights applet into community. The applet displays the current Northern Lights data from the NOAA including the KP index, wind speed, Bz, and a brief summary of the most resent NOAA notifications. This data will show you the current space weather conditions for aurora level estimates.
I have read the CLA Document and I hereby sign the CLA

PR to add new Northern Lights Applet

---

apps/pgatour/pga_tour.star

Bug fix for completed rounds
Updated opposite field events & check

Bug fix: PGA Tour

---

apps/martamap/marta_map.star

New api for the MARTA train arrivals

Update: MARTA Map New Arrivals API

---

apps/visualizercoffee/visualizercoffee.star

The compare logic of timestamps needs to all be in the same location.

[app/visualizercoffee] fix timestamp timezone

---

apps/steamtopsellers/steam_top_sellers.star

Padded game name for more consistent display animations in marquee.

[Minor Update] Steam Top Sellers

---

apps/visualizercoffee/visualizercoffee.star

time compare currently is now() vs the intended day today starting at midnight.

apps/visualizercoffee: update compare time to midnight of the same day

---

apps/milbscores/milb_scores.star

Updated status check for completed games

Update: MiLB Scores

---

apps/pregnancytracker/manifest.yaml
apps/pregnancytracker/pregnancy_tracker.star

Track your baby's size throughout the duration of your pregnancy. Provide your baby's due date and see the fruit or vegetable to which your baby is closest in size each week.

Pregnancy Tracker v1.0.0

---

apps/belifeed/beli_feed.star

Neglected this for a while, but updated to the new Beli API

Update Beli Feed app

---

apps/hackernews/hacker_news.star
apps/hackernews/manifest.yaml

[Hacker News](https://news.ycombinator.com/news) is a somewhat popular link-sharing community that tends to discuss Startups, New Technology, Software Development, and a lot more tech or just plain interesting things.
This app will curate the top 3 stories (or links) from the last 2 days and display them on your Tidbyt.
Here is a preview:

New App: Hacker News

---

apps/gvbyt/gvbyt.star

Pass a typical user agent when querying the GVB API.

bugfix - passes typical user agent

---

apps/company_clock/company_clock.star
apps/gradientclock2/gradientclock2.star

This fixes an issue with incorrect timezone handling on the app, as reported by the user candido in the forums: https://discuss.tidbyt.com/t/the-time-on-the-new-clock-apps-are-two-hours-wrong/6543
@qqvq-d we need your approval here.

[FIX] Company Clock: incorrect timezone handling

---

apps/nycbus/nyc_bus.star

Sorting the locationbased options by (euclidean) distance. Makes it easier
to find the right stop.

nycbus: order stop by distance to location

---

apps/mongodbnotify/README.md

Updated the README.md with some notes which I thought might be helpful for someone setting this up.

updated README.md with some notes

---

apps/mongodbnotify/README.md
apps/mongodbnotify/mongodb_notify.star

Fixed the sorting in the app.
Updated the README.md to reflect the changes I made to how pages are stored in MongoDB.

Fixed the sorting of the messages; Corrected the out of date README.md

---

apps/mongodbnotify/README.md

Updated README.md with a bit more information to get people started.

updated README.md with a bit of info on Setting up Atlas

---

apps/rssreader/manifest.yaml
apps/rssreader/rss_reader.star

This app is a generic RSS feed reader. The user can input the feed URL and view articles' titles and (optionally) their content.
Inspired by @jvivona's RSS apps, also uses some portions of the code. Thanks! 😉

New App: RSS Feed Reader

---

apps/dateprogress/date_progress.star
apps/fivesomewhere/five_somewhere.star
apps/jacket/jacket.star
apps/mbta/mbta.star
apps/nycbus/nyc_bus.star

Experimenting with alternative display modes for some apps.
This may get reverted.

experimental widget mode for a few apps

---

apps/rssreader/rss_reader.star

Small update to the Generic RSS Reader app to include an option to use a larger font.

Update: RSS Reader - add option to use a larger font

---

apps/olympic_medals/manifest.yaml
apps/olympic_medals/olympic_medals.star

This update adds a second display option to the app where the user can track the medals of a specific country.
Preview:

Update: Olympic Medals: add option to track a specific country

---

apps/adelaidemetro/adelaide_metro.star

Addition of Port Dock station and route, opening 25th August

Update: Adelaide Metro

---

apps/vidiotscalendar/manifest.yaml
apps/vidiotscalendar/vidiots_calendar.star

This app displays showtimes for the next 7 days at [Vidiots](https://vidiotsfoundation.org), a movie theater and video store in Eagle Rock, Los Angeles. Movies and showtimes are obtained by scraping the calendar page from their website. I'm friendly with the people who run the theater (and am, in fact, a founding member of Vidiots) so I'm reasonably sure this should be OK.

New App: Vidiots Calendar

---

apps/melbournetrains/melbourne_trains.star

**Added:**
- New Station: East Pakenham Station

Update: Melbourne Trains

---

apps/atptennis/atp_tennis.star
apps/wtatennis/wta_tennis.star

Fixed bug that may show only 1 or no players in a scheduled match, should now only display a scheduled match when both players are listed

Bug fix: ATP Tennis & WTA Tennis

---

apps/goldpriceticker/goldpriceticker.star

Removed legacy cache module, replaced with http caching - reenabled time series

---

apps/militarynews/military_news.star

Delay needs an int, not a string.

Fix bug with show instructions.

---

apps/fredscanneralert/fredscanner_alert.star

Changed scrolling speed - Slowed it down some.

Update fredscanner_alert.star - Scrolling Speed Change

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Tidy up logic for displaying clock/IOB/COB, graph, etc
Clean up spacing for all modes
Linting

Nightscout - v2.5.2 Re-org display spacing

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

A minor update to fix Stale Reading Display Spacing on Large Clock

Nightscout - Minor Update - Stale Reading Display Spacing on Large Clock

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Another minor spacing tweak for stale readings with clock and no graph
(sorry, I think this one is finally right)

NightScout - Another Quick Spacing Tweak

---

apps/melbournebuses/melbourne_buses.star

**Bug Fix:**
- `schema.LocationBased()` was being used incorrectly in the previous PR:
- As a result, the schema location config always defaulted to using the `default location` instead of the `actual location` the user entered

Fix: Melbourne Buses - Default location was always triggered

---

apps/meeting_stats/meeting_stats.star
apps/outlookcalendar/outlook_calendar.star

Removed the (spurious) redirect_uri parameter that was throwing errors for some users

Urifix sept2024

---

apps/colorado14ers/colorado14ers.star

Take advantage of updated Tidbyt app and display which Range each mountain is in. Update instructions.

Update instructions, add descriptions.

---

apps/nhllive/nhl_live.star

- Added in Utah team & logo reference
- Removed caching of next game local start time. Only cache the UTC time and then convert to local if game is FUT/PRE
- Fix issue where situationCode (PP/EN) can get stuck on.

NHL LIve: Updating to add Utah and fix some last season bugs

---

apps/snakeclock/manifest.yaml
apps/snakeclock/snake_clock.star

Adds a new app:
- shows a clock in the foreground
- background shows a snake moving around in a random pattern
- using global state to sync the movement for all users
- this means every user will see the same snake movements 🎉

New App: Snake Clock

---

apps/melbournebuses/melbourne_buses.star

- Change `Bus Location` to `Bus Stop Location` in schema config

Refractor: Melbourne Buses

---

apps/stripespotlight/manifest.yaml

Updates the description of Stripe Spotlight to match the updated functionality. Had made changes to the applet prior to submission yesterday to follow the date ranges that are available by default in the Stripe Dashboard and never reflected those updated values in the description after testing. 🙈

Update: Stripe Spotlight

---

apps/git_commit_humor/git_commit_humor.star
apps/git_commit_humor/manifest.yaml

Displays humorous Github Commits in a scrolling fashion using the whatthecommit (https://whatthecommit.com/index.txt) API. The app will rotate through fonts and color based on commit text length.

New App: Git Commit Humor

---

apps/haikuboxlinker/haikuboxlinker.star
apps/haikuboxlinker/manifest.yaml

Another attempt after redoing the whole app setup with my git email and name set correctly.

Haiku box data transfer

---

apps/wowcharacterstats/README.md
apps/wowcharacterstats/wowcharacterstats.star

- Update current expansion and raid
- Add character level and faction stats
- Use marquee to scroll stats
- Add color coding to raid progress

WowCharacterStats: Update current expansion and raid

---

apps/twsestock/manifest.yaml
apps/twsestock/twse_stock.star

Add new app: TWSE Stock
Display TWSE stocks
This is the first app I'm submitting, so please let me know if anything needs changes or adjustments. Thanks

New App: TWSE Stock

---

apps/vipabfahrten/manifest.yaml
apps/vipabfahrten/vipabfahrten.star

This app shows departures of public transportation service in Potsdam, Germany (https://www.swp-potsdam.de/de/verkehr/).

New App: ViP Abfahrten

---

apps/billboardtop10/billboardtop10.star

Since I only need to call this API a couple times a week (fewer if I knew when the data updated I suppose), no need for everyone to get their own RapidAPI key. So removed that, removed instructions to do it. 
Added option to display only top 5 in addition to full Top 10 list.

No longer need your own API Key. Can display top 5 or top 10

---

apps/us_polling_average/manifest.yaml
apps/us_polling_average/us_polling_average.star

Shows the latest 2024 US Presidential polling averages from FiveThirtyEight!
From https://projects.fivethirtyeight.com/polls/president-general/2024/national/

US Polling Average from FiveThirtyEight

---

apps/us_electoral_forecast/manifest.yaml
apps/us_electoral_forecast/us_electoral_forecast.star

Shows the current US electoral vote and popular vote forecast from 538.
Estimated electoral vote count:
Estimated popular vote:
Win probability:
(from https://projects.fivethirtyeight.com/2024-election-forecast/)

US Electoral Forecast from FiveThirtyEight

---

apps/tagesschau-news/.gitignore
apps/tagesschau-news/manifest.yaml
apps/tagesschau-news/tagesschau_news.star

New App: tagesschau_news

---

apps/minecraftrealms/manifest.yaml
apps/minecraftrealms/minecraft_realms.star

It will show the status of a Minecraft Bedrock Realms server.
It chooses one you are apart of at random (for now) and shows the realm name, how many players are currently online, the realms description / message of the day (MOTD), and the active world slot via the circle's colour.
- Add player names and hopefully their character's skin's head 8px square image.
- <https://mineskin.eu> as provided by an API similar to this one's but for the Bedrock edition.
- Better and custom realm selection (don't show closed or expired realms, show one that I am logged into, show specific one(s) only, etc.)
- Fun backgrounds?
- Better and more aesthetic error messages
Please send me any suggestions for features you'd like to see in this app, I want it to be as fun and useful for all Minecraft gamers!

New App: Minecraft Realms

---

apps/solarweatherclock/manifest.yaml
apps/solarweatherclock/solarweatherclock.star

New app that displays the current grid export of solar from home assistant as well as the weather and time

new app: solarweatherclock

---

apps/bgglastplay/bgg_last_play.star
apps/bgglastplay/manifest.yaml

Simple app that displays the number of days since the last time the given user has recorded a play on board game geek; I eventually want to pretty it up a bit, but this is a good first iteration.

New App: Bgg Last Play

---

apps/nascarnextrace/nascarnextrace.star

add highlight for folks clinched into playoff rounds into playoff points

NASCAR: Feat - add highlight for folks clinched into playoff rounds

---

apps/whatthecommit/manifest.yaml
apps/whatthecommit/whatthecommit.star

New App: Whatthecommit

---

apps/tankerkoenig/manifest.yaml
apps/tankerkoenig/tankerkoenig.star

New App: Tankerkoenig

---

apps/pull_request_status/manifest.yaml
apps/pull_request_status/pull_request_status.star

New App: GitHub PR status

---

apps/twbaseballcpbl/manifest.yaml
apps/twbaseballcpbl/tw_baseball_cpbl.star

Upcoming game:
Live game:
Final:
Add new app: TW Baseball CPBL
Display CPBL scores
Please let me know if anything needs changes or adjustments. Thanks

New App: TW Baseball CPBL

---

apps/randomrecipe/manifest.yaml
apps/randomrecipe/random_recipe.star

New App: random recipe

---

apps/caltrain/caltrain.star

I did a whoopsie dooopsie with the date, but now it should be fine just to remove the date check altogether as the new schedule is in full effect.

[Caltrain] remove date check

---

apps/weathersnapshot/weather_snapshot.star

Added personal API Key schema (config) value to allow more frequent updates (every 10 minutes vs every 6 hrs). Changed weather API to free tier that does not require a credit card. Original functionality is maintained if no personal API key is provided (will still use the provided hashed API keys in file and cache/query every 6 hrs).

Update Weather Snapshot to allow use of personal api key

---

apps/bblcricket/bbl_cricket.star

Updated for upcoming 2024/25 season

Update: BBL Cricket

---

apps/qbittorrent/qbittorrent.star

* Login endpoint should be a POST
* Add category filter

qbittorrent: fix login (POST) and add category

---

apps/sleeperfantasyfootball/sleeperfantasynfl.star

update to try and get the current nfl season so it works for every year and not just 2023

Sleeperyearfix

---

apps/worldtides/manifest.yaml
apps/worldtides/world_tides.star

Based on NOAA Tides app.
This app is visually identical to NOAA Tides but uses the stormglass.io API to enable global tide location.  It requires a free personal API key producred and entered by the user.

new World tides app

---

apps/twbaseballcpbl/tw_baseball_cpbl.star

The type of `game_info["CurtBatting"]["VisitingHomeType"]` should be string

fix: inning symbol variable type issue (TW Baseball CPBL App)

---

apps/nightscout/manifest.yaml
apps/nightscout/nightscout.star

Improved error messages and layout

Nightscout: 2-6-2-improved-error-handling

---

apps/nhllive/nhl_live.star

NHL changed their API again. Also added a minor fix for Game Day Only.

Update NHL Live Live Update Endpoint 

---

apps/espnffstandings/espn_ff_standings.star
apps/espnffstandings/manifest.yaml

display fantasy football standings for ESPN app

ESPN fantasy football standings

---

apps/soccertables/soccer_tables.star

Added three UEFA competitions to the selectable leagues - Champions League, Europa League and Europa Conference League

Update: Soccer Tables

---

apps/bgglastplay/README.md
apps/bgglastplay/bgg_last_play.star

This is what it looks like without the labels
"days since" label
"last play" label

BGG last play update: display game cover art

---

apps/tennisrankings/tennis_rankings.star

Update: Tennis Ranking

---

apps/bkkschedule/bkk_schedule.star
apps/bkkschedule/manifest.yaml

**BKK Schedule app**
An app to display Budapest public transit departures for a stop. So far fairly basic, I'm planning on adding warnings and support for multiple stops eventually.

BKK Schedule app

---

apps/librenmsdevices/librenms_devices.star

Minor bug fixes and refactoring; added demo data.

Updates to LibreNMS Devices app 2024-10-07

---

apps/datadogcharts/datadog_charts.star
apps/datadogmonitors/datadog_monitors.star

fix some issues with datadog apps

---

apps/librenmsalerts/librenms_alerts.star

Updated refresh speed. Misc. bug fixes.

LibreNMS Alerts: Updated display refresh speed; misc. fixes

---

apps/wfmu/manifest.yaml
apps/wfmu/wfmu.star

Displays what's currently playing on WFMU. WFMU-FM 91.1/Jersey City, NJ; 90.1/Hudson Valley.

Add new app: WFMU

---

apps/nowspinning/README.md
apps/nowspinning/manifest.yaml
apps/nowspinning/now_spinning.star

This app was developed by request for the user `Diesel7688` on the [Tidbyt Forums](https://discuss.tidbyt.com/t/now-spinning/6964).
It displays the album cover, album name and artist name from a specific album chosen by the user.
The app itself is not connected to any music service and does not update automatically. The user needs to manually change the displayed album. This behavior was also by request.
Preview:

New app: Now Spinning

---

apps/halloweencountdn/halloween_countdn.star

Updated Halloween Countdn app to say "Halloween" on Halloween instead of "0 days".

update halloween_countdn app to change display on Halloween

---

apps/nowspinning/now_spinning.star

Added an option to control the font sizes for album and artist individually.
Also added a fourth "Extra Large" font size option.

Update Now Spinning app: add option to control font sizes individually

---

apps/wowtoken/README.md
apps/wowtoken/manifest.yaml
apps/wowtoken/wow_token.star

Converted the application to utilize a new API to retrieve data

wowtoken - updated api

---

apps/rachio/rachio.star

Fixed method to display the current zone that is watering at the moment.  Found way to know if there is a 'current' job running, or instead, a recent job to display. 
Allow user to display the device name on Tidbyt to help distunguish multiple rachio units.

Rachio updates

---

apps/thisdayhistory/manifest.yaml
apps/thisdayhistory/this_day_history.star

new app to replace broken Today in History app.   
Supports both English and Spanish
Display 1 random historical event, 1 random person born and 1 random person who dies (if you select those options) today.  Uses Wikipedia information. 
Muestra eventos históricos de hoy, incluyendo nacimientos y defunciones (si se selecciona). Usa información de Wikipedia.

New App: This Day in History

---

apps/thanksgivingday/thanksgiving_day.star

Hack since we don't actually have calendar functions in Starlark.

thanskgivingday: Fix for 2024

---

apps/congresswatch/congress_watch.star

Some code cleanup, new icon, and handle case where secret.decrypt comes back blank.

Handle case where API Key is blank (Demo, build). Update image.

---

apps/shipweatherclock/manifest.yaml
apps/shipweatherclock/shipweatherclock.star

adding an app that displays:
1. Text of
- current time
- low and high temperatures for the day
- current temperature
2. Ship on the ocean scene with:
- wave animations based on windspeed
- sun and moon that rise/fall based on time to sunrise/sunset
- sky colors that change based on day/night/sunrise/sunset
- clouds and precipitation based on current weather

publishing new app: shipweatherclock

---

apps/thingswifesays/things_wife_says.star

Reducing space on image box by a few pixels and adding it on the text box to prevent words from cutting off

spacing changes to reduce cutting off words

---

apps/rachio/rachio.star

Forgot to apply the correct time zone to the time new time displays.

Apply correct time zone to display dates.

---

apps/thisdayhistory/this_day_history.star

This PR adds german language to the App "This Day in History".
@jvivona: Hope you approve.

App "This Day In History": add german language

---

apps/victron/manifest.yaml
apps/victron/victron.star

Hello,
This is a new app that integrates with the Victron VRM API to show energy data for a given Victron installation. API key is provided in the config to render actual data. Here is a sample:

added new victron module

---

apps/gartnernews/gartner_news.star

use http cache
update headers and user-agent

Gartner update

---

apps/qbittorrent/qbittorrent.star

Add the option of having no torrents show (only show the down and up speed)

qbittorrent add 0 option

---

apps/stockdata/stockdata.star

Add 5 and 10 minutes as refresh interval options

stockdata: add more refresh intervals

---

apps/atptennis/atp_tennis.star
apps/wtatennis/wta_tennis.star

Updated both apps for 2025 seasons

Update: ATP Tennis & WTA Tennis 

---

apps/aflladder/afl_ladder.star
apps/aflscores/afl_scores.star

Updated both apps for the 2025 season

Update: AFL Scores & AFL Ladder

---

apps/atptennis/atp_tennis.star

Bug fix - for when there is a tournament listed in the data feed but has null info

Fix: ATP Tennis

---

apps/wsjnews/wsj_news.star

thanks to @shimonsavitsky for the new URL for WSJ News.
added sections from recommendations

update: WSJ News - fix URL for feed and add sections

---

apps/nextufc/next_ufc.star

Update: Next UFC

---

apps/newsmix/manifest.yaml
apps/newsmix/news_mix.star

News Mix is a customizable news reader that displays rotating headlines from your choice of major news sources. The app cycles through three different feeds, showing headlines and descriptions in a clean, scrolling format simlilar to the default News App. 
- Support for multiple news sources including WSJ, NYT, BBC, CNN, NPR, The Guardian, and TechCrunch
- Customizable feed selection (choose any 3 feeds)
- Instead of showing only 1 story for each source, show top 3 stories from each source by randomly selecting one each time. As a result, up to 9 news will be shown to the users
- Color customization for feed names, headlines, and descriptions
- Adjustable scroll speed
- Smart error handling with fallback to alternate feeds
- Efficient caching system to minimize API calls
1. Configure at …

Add a new app News Mix: Multi-source RSS news reader with customizable feeds

---

apps/wowcharacterstats/wowcharacterstats.star

Updated app to reflect latest raid

Wowcharacterstats undermine update

---

apps/shippingforecast/manifest.yaml
apps/shippingforecast/shippingforecast.star

This app displays the forecast for a chosen location in the style of the Shipping Forecast. Displays the wind, conditions, and visibility. The app calls a REST API that I build as well, which does the work of generating the forecast in the correct style.

New App: Shipping Forecast

---

apps/relay_fm_live/manifest.yaml
apps/relay_fm_live/relay_fm_live.star

Remove more ".fm" references from the Relay app

Relay fm update

---

apps/trolley_detector/manifest.yaml
apps/trolley_detector/trolley_detector.star

Handle "N/A" in direction of travel

Septa g1 direction update

---

apps/pgatour/pga_tour.star

Incorrect Tournament ID for The Players

Fix: PGA Tour

---

apps/steam_plus/steam_plus.star

removing an unused import causing issues in a community project.

Remove unused secrets.star import from steam_plus app

---

apps/goodservice/goodservice.star

* Set Third Time config default to Off instead of 3 mins delta.

The Weekendest: Change default Third Time config to off

---

apps/sanflscores/sanfl_scores.star

Resolved issue where team records were not displaying correctly.

Fix: SANFL Scores

---

apps/sanflladder/manifest.yaml
apps/sanflladder/sanfl_ladder.star

A new app that shows the SANFL League Ladder. A perfect compliment to the SANFL Scores app!😉

New App: SANFL Ladder

---

apps/nola-streetcar/manifest.yaml
apps/nola-streetcar/nola_streetcar.star

New Orleans streetcar departure times

feat: Add NOLA Streetcar apNp

---

apps/sanflscores/sanfl_scores.star

Using logic to work out when the next round starts rather that relying on the data from Ladder API

Update: SANFL Scores

---

apps/anycalendar/any_calendar.star
apps/anycalendar/manifest.yaml

Any Calendar allows users to display theirs or a shared calendar simply via an .ics link, without requiring a login and authorization. It works for both Google and Outlook calendars as long as the calendars are public. This is a nice alternative to the Tidbyt official Google Calendar app.
The app first checks if there's a current event, and if not, then it checks if there's an upcoming event, and if not, then it checks if there's an all day event, and if not it skips the app from the rotation.
There are color customization options as well as the ability to show or hide the event time. With the time hidden, this app is a really great way to display scheduled announcements, perfect for family reminders, shop messages, businesses, etc.

add anycalendar app to community apps

---

apps/faaatis/faa_atis.star
apps/faaatis/manifest.yaml

Adds an app which uses 2 APIs to fetch and parse FAA ATIS information to display current information code and arriving / departing runways.

new app: FAA ATIS

---

apps/faaatis/faa_atis.star

update: rotate secret, remove unencrypted value

---

apps/sanflladder/sanfl_ladder.star
apps/sanflscores/sanfl_scores.star

Update to both SANFL Scores & SANFL Ladder
**SANFL Scores**
Reduced match cache time for the weekend. We need check more often when the games are about to start
Added leading zero for when seconds on game clock is <10
**SANFL Ladder**
Updated API URL and reduced cache for the weekends, similar to Scores app

Update: SANFL apps

---

apps/planesoverhead/planes_overhead.star

This Pull Request changes the backend API referenced by the `get_typecode` function.

change typecode lookup backend for planesoverhead app

---

apps/germanpartypolls/germanpartypolls.star
apps/germanpartypolls/manifest.yaml

New App: German Party Polls

---

apps/atb-bus-times/atb_bus_times.star
apps/atb-bus-times/manifest.yaml

A Tidbyt app that displays real-time bus departures from ATB stops in Trondheim, Norway.
- Shows the next three departures from selected bus stops
- Displays line numbers and departure times
- Updates in real-time
- Shows "Nå" when the bus is due to depart within the next minute
Users can configure:
- `stop_id`: The Entur ID for their bus stop (e.g., "NSR:StopPlace:42052")
- `quay_id`: The specific platform ID at their stop (e.g., "NSR:Quay:71981")
- `stop_name`: The display name for their stop (e.g., "Valøyvegen")
The app has been tested with:
- Real-time data from the Entur API
- Various bus stops in Trondheim
- Different time formats and display scenarios

Add ATB Bus app

---

apps/worldcapitals/worldcapitals.star

Show "No Capital City" instead of `Error: index 0 out of range: empty list`

worldcapitals: handle countries without capital cities

---

apps/cyclecast/cyclecast.star

In some cases the humidity was off-centered from the box it was supposed to be in.

Fix off-centered humidity reading.

---

apps/nsbyt/nsbyt.star

Adds an optional indicator to show if you need to run for the train or not.

Update NSByt app

---

apps/f1results/f1_results.star

Updated for new API
Added DQ status as well for disqualified drivers/cars

Update: F1 Results

---

apps/customquotes/custom_quotes.star
apps/indianews/india_news.star

1. App was broken because image service was broken. replaced with a more stable service (picsum.photos) to resolve timeout issues.
2. Increases spreadsheet range from 500 to 1000 rows

fix: change image service to picsum.photos to resolve timeout issues

---

apps/pixelartclock/manifest.yaml
apps/pixelartclock/pixel_art_clock.star

App to display the current time and the day's max/min temperatures, with an illustrated background by [@abipixel](https://www.instagram.com/abipixel/) matching weather conditions. Some of the illustrations are animated.
Illustrations were commissioned to Abipixel by myself and I have the right to use them.

New App: Pixel Art Clock

---

apps/aflscores/afl_scores.star

Added Indigenous team names used during Indigenous Round , and at other times during the season

Update: AFL Scores

---

apps/loanpayment/loan_payment.star
apps/loanpayment/manifest.yaml

I created this app so that I have a good overview of how much of my student loan I still have to pay back. You can always use it to display the remaining monthly repayment amount.

feat(loanPayment): add loan payment countdown app

---

apps/pathtimes/manifest.yaml
apps/pathtimes/path_times.star

This implements a NJ PATH trains schedule, similar to the default/built in NY metro app. This uses the official PATH train website which publishes real time data as a simple JSON file - we only hit this API twice a minute.

New app: PATH Times

---

apps/culvers/culvers.star
apps/culvers/manifest.yaml

This app displays the flavor of the day at Culver's.
(This is somehow the third frozen custard-related app I've made for the Tidbyt, but this is also my first one for a chain with more than 3 locations across the US. Each one has a different flavor of the day, and I'm proud of figuring out how to make a `LocationBased` schema field for this.)

New App: Culver's

---

apps/gw2_fractals/gw2_fractals.star

This adds the new Guild Wars 2 Fractal of the Mist "Kinfall" to the app data.

feat: add Kinfall to GW2 FOTM rotation

---

apps/chicagodivvy/chicago_divvy.star

- the station ID changed and was no longer showing a valid screenshot in the Tidbyt app

Use static data for screenshot

---

apps/exotic_clocks/exotic_clocks.star

Fixing rendering bug for Korean words when the minute is a multiple of ten.

exotic_clocks: bug fix

---

apps/lolstats/lol_stats.star
apps/lolstats/manifest.yaml

A new app that shows League of Legends player data. It contains 4 rows:
1. Shows player name and Rank
2. Shows total player stats: wins / losses and current League Points
3. Shows last match data: win/loss, champion played, KDA, Gold and Minions killed
4. Shows a list of W/L representing wins/losses on the last few matches
Configuration allows you to set the summoner name, tagline and region. If not set, it will pick from a small pool of famous players to display.
Requires setting a RIOT API key (free to get for development but only lasts a day). Still working through the process to obtain a RIOT production key API and will put a follow up PR with it in the project.

New: lolstats - show League of Legends player data

---

apps/neotracker/manifest.yaml
apps/neotracker/neo_tracker.star

This app pulls from my own AWS Lamdba function to get the top 10 closes NEOs passing by within the next week. The app displays them 1 second at a time. 
The Lamda request only hits the NASA NEO API once a day, then returns the cached data for the Tidbyt app.

Adding NEO Tracker app by Jordan Fitzpatrick

---

apps/mtgscryone/manifest.yaml
apps/mtgscryone/mtg_scry_one.star

This adds a new app to Community: MTG Scry One, which renders and shows a random Magic: The Gathering card, along with some options.

New app: MTG Scry One

---

apps/atptennis/atp_tennis.star
apps/wtatennis/wta_tennis.star

If the next scheduled match is the Final, then look ahead 48hrs instead of the normal 12hrs to make the final appear sooner in the list of 'scheduled matches'

Update: ATP & WTA Tennis 

---

apps/domewatch/dome_watch.star

This PR updates the dome_watch app with several improvements to enhance the user experience:
- **Real-time timer animations**: Smooth count-up/count-down animations for voting timers
- **Improved timer format**: Displays H:MM:SS format for timers exceeding 1 hour
- **Continuous scrolling**: Vote questions now scroll continuously for better readability
- **Enhanced robustness**: Better error handling for timer edge cases
- **Mock mode**: Added development/testing mode for easier debugging
- Implemented dynamic voting timer with animation frames
- Added logic to switch to H:MM:SS format after 1 hour
- Improved marquee scrolling for vote questions (10x repetition for continuous effect)
- Added MOCK_MODE configuration for testing different timer states
- Enhanced error handling for API …

Update domewatch: Add real-time timer animations and improved timer format

---

apps/pentagonpizzaix/manifest.yaml
apps/pentagonpizzaix/pentagon_pizza_ix.star

I've created my own Pentagon Pizza Index inspired by https://www.pizzint.watch/. 
I've backed this app with a custom data collection in supabase that serves as the back end to deliver the data for display.

New App: Initial version of pentagon pizza index

---

apps/usgswaterlevels/manifest.yaml
apps/usgswaterlevels/usgs_water_levels.star

This is a super basic app, written mostly with the help of Claude, to display USGS data. It polls the API once an hour, and shows a few different data codes - depth and temperature. The top marquee is the station name, the vertical column on the right calculates the high and low points for the past 30 days, and displays today's measurement as an X relative to those highs and lows.
This is my first attempt at submitting anything, anywhere, so please let me know what I should do better! (actually, this is my second attempt. I submitted the first pull request about ten minutes ago with the wrong GitHub username, because I am that new at this!)

USGS Water Level and Temp App

---

apps/bored/bored.star
apps/bored/manifest.yaml

Removed HTTP Dependency and Added Local Activities
- Eliminated broken boredapi.com HTTP service dependency
- Implemented hardcoded list of 140+ diverse activities across categories: reading, cooking, physical activities, creative arts, silly/absurd activities, nature, technology, and
wellness
- Each activity includes effort level rating (0.0-1.0) for difficulty assessment
Enhanced Visual Design
- Added colorful effort meter with 21-step gradient from green (easy) to red (hard)
- Implemented effort level indicator with position marker on gradient bar
- Changed effort text color to white for better readability
- Updated fonts for improved visibility
Improved User Experience
- Random starting position in activity list (cached per user)
- Sequential cycling through activities with proper …

Bored App Modernization and Enhancement

---

apps/rainbows/README.md
apps/rainbows/manifest.yaml
apps/rainbows/rainbows.star

New Tidbyt app that displays beautiful animated rainbow effects with multiple animation styles to brighten up any display! 🌈
- **Four unique animation styles**: Magic, Drops, Smoke, and Farts
- **Configurable** animation selection through Tidbyt app settings
- **Smooth, optimized animations** designed for 64x32 pixel displays
- **No external dependencies** - all animations are self-contained
- **Performance optimized** for smooth playback
- `apps/rainbows/rainbows.star` - Main application code
- `apps/rainbows/manifest.yaml` - App manifest and configuration
- `apps/rainbows/README.md` - Comprehensive documentation
Perfect for adding colorful joy to any Tidbyt display! ✨

 🌈 Add Rainbows app - animated rainbow effects for Tidbyt displays
