tidbyt/community

apps/apps.go, apps/dvdlogo/dvd_logo.star, apps/dvdlogo/dvdlogo.go
This PR introduces the Bouncing DVD Logo app to the community repo! The app was created with the `make app` command and the code was copied from [`mackorone/tidbyt-bouncing-dvd-logo`](https://github.com/mackorone/tidbyt-bouncing-dvd-logo). The app computes and renders 30 seconds worth of frames, and the starting state is a function of the current time.
=> Add Bouncing DVD Logo app

apps/bigclock/big_clock.star, apps/bigclock/bigclock.go
Changing for day or night is such a great feature! We wanted to make sure we can support it natively. I've updated this app to use our new module to serve as a good example for folks who are looking to do the same in their app.
- big-clock: Swap to new sunrise/sunset module.
- This commit utilizes the newly added sunrise module to get the sunrise/sunset times natively!
- big-clock: Remove truncation.
- This commit removes the truncation for the location. We're no longer sending it to an external API, so we're not leaking any privacy information.
=> big-clock: Swap to new sunrise/sunset module.

Makefile
* Add `format` as a synonym for `lint`.
* Don't require golangci-lint to be installed.
* Check for and install buildifier when running lint.
=> Make lint more user-friendly

apps/sunrisesunset/sunrise_sunset.star
This commit fixes an issue where the default for config.get() is to
return a string, which is always truthy. Now we are using config.bool()
which will handle the type cast for us to ensure the string "False" will
actually return as `False`.
=> sunrise-sunset: Fix bool for 24 hour time.

apps/binaryclock/binary_clock.star
The default values in schema need to be the actual option values and not
the option text.
=> binaryclock: Fix defaults

apps/dateprogress/date_progress.star
While testing the configuration, I noticed that the "Show percentages" option was not hiding the percentage labels.
Before:
After:
=> [Date Progress] Hide progress labels

apps/sbbtimetable/sbb_timetable.star
This PR now treats the return parameter from the typeahead as JSON.
=> SBB Timetable App: Handle JSON return parameter from typeahead

apps/apps.go, apps/pagerduty/pagerduty.go, apps/pagerduty/pagerduty.star
This PR adds a new app for displaying the number of total open and triggered/unacknowledged incidents for a user's account.
This is my first attempt at using [`schema.OAuth2`](https://github.com/tidbyt/pixlet/blob/main/docs/schema/schema.md#oauth2). PagerDuty does return refresh tokens, but they[ aren't currently usable](https://community.pagerduty.com/forum/t/auth-code-grant-flow-refresh-token/208). Tokens issues by PagerDuty do not expire unless they are revoked by the user.
There are a few configuration options that control the app's display when a user is on-call
* The user may completely disable the on-call bar.
* The user may choose to only treat on-call shifts where they are the level one escalation path to be on-call.
* The user may choose to completely hide the app from …
=> pagerduty: Initial PagerDuty stats

apps/bigclock/big_clock.star
This commit adds defaults for schema toggless. The issue is, we don't know where
the toggle should be by default if these are not set. For most toggles,
the default is False, and config.get("foo", False) typically defaults to
False. But in this case, the default is False but the config value
defaults to True in some cases.
=> bigclock: Set defaults for schema.

apps/apps.go, apps/hvvdepartures/hvv_departures.star, apps/hvvdepartures/hvvdepartures.go
This app displays real-time departure times for trains, buses and ferries in Hamburg (HVV) using APIs exposed by https://transport.rest/
It has a lot of configuration options including:
* Picking a station via typeahead.
* Picking a direction via typeahead.
* Picking a departure time formats:
- Relative (e.g. "3 min")
- Absolute 24-hour format + delay indicator (e.g. "09:30+3")
- Absolute 12-hour format + delay indicator (e.g. "01:30 PM+2")
* Picking a departure time offset, if it takes some time to get to the departure station by foot.
- now
- in 5 minutes
- in 10 minutes
- in 15 minutes
* Selecting which means of transport to include:
- Subway (U-Bahn)
- Suburban trains (S-Bahn)
- Commuter trains (AKN)
- Buses (MetroBus, XpressBus, NachtBus)
- Regional (express) trains (Regional-Bahn, …
=> Add 'HVV Departures' app.

apps/nationaltoday/nationaltoday.star
The `if-else` statement had it's conditions flipped, so it would show an error when data was grabbed successfully.
=> National Today: Fixed errors in getting the data

apps/apps.go, apps/gapilotbuddy/ga_pilot_buddy.star, apps/gapilotbuddy/gapilotbuddy.go
This app uses a user-chosen location and a third-party API for nearby aerodromes and their current flight rules and METAR (weather) information. For General Aviation pilots, having this information available at a glance is invaluable as it's the first step in making a go-no go flight decision. I did not include full METAR information as it would probably be a bit too long-form for horizontal marqueeing but the chosen fields are the most relevant.
The app only has one other option other than location, which is "Show All Aerodromes". By default, non-public aerodromes are filtered out; however, if this is enabled, non-public ones such as military or private will also be shown.
Just FYI, flight rules color coding goes like this:
So in this example, all 3 local airports are VFR (just how I …
=> Add GA Pilot Buddy app

apps/apps.go, apps/nft/nft.go, apps/nft/nft.star
This widget connects to the Opensea api and fetches a random NFT to display for a given public address. The default address configured is for https://opensea.io/GaryVee
=> Widget to display a random NFT associated with an Ethereum Public Address

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR adds a [devcontainer](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-codespaces-for-your-project) configuration for [Github Codespaces](https://github.com/features/codespaces) to the Community repo.
It configures a Go dev environment, clones and builds the latest version of Pixlet and makes it available in the user's `$PATH`. The Bazel and Go VSCode extensions are installed automatically as well.
This allows anyone to click on Codespaces in the community repo and be creating apps right in the browser with no set up required. When they go to commit it tells them they don’t have permissions to push to the repo and asks to make a fork. If the user chooses to fork, Github makes a new fork and then offers to create a PR automatically.
Running …
=> Add devcontainer configuration for Github Codespaces

docs/guides/publishing_apps.md
Changed appaname to appname, which is what I think the author meant and is consistent with other references to the app directory.
=> Fix Typo in Publishing Apps guide

apps/apps.go, apps/sportsscores/sports_scores.star, apps/sportsscores/sportsscores.go
This currently allows for MLB and NHL daily scores around the league. Data is pulled every minute (this could be changed since it will take longer than a minute for the app to come back around)
Have tested the MLB with old data and current NHL data.
There is also a frame speed setting to change how quickly the frames change. 
Word of note, spacing between frames may differ depending on contents, but within a frame it will space out evenly.
Random MLB day from last year:
Current MLB:
NHL pulled earlier today:
=> Add Sports Scores App

apps/lirr/lirr.star
After testing the LIRR app in the Tidbyt app, I found two bugs that this pull request attempts to fix.
1. The stops were showing up in id order rather than closest to farthest
2. All times from the api the app uses are in "local time"/ Eastern time as that is where the trains are located. The time.now() is giving times based on UTC so it's currently showing trains 5 hours in the future (this was due to a timezone issue so my local machine was giving proper times but Tidbyt's servers are not)
=> Fix bugs with lirr app

apps/tempest/tempest.star
This matches what the tempest website uses to display pressure.
See: https://discuss.tidbyt.com/t/tempest-weather-showing-wrong-pressure-value/1360
=> update tempest weather to use sea level pressure

apps/nycbus/nyc_bus.star
* fix issue reading stop_code from LocationBased schema
* ensure time.now is always in new york time zone
* do some more logging if there's an issue with the json response
* show something when there's no buses
* gracefully handle when there's only one bus
**regular**
**one bus**
**no buses**
fixes #231 
cc @rohansingh
=> nycbus: fix schema usage and some small improvements

.devcontainer/devcontainer.json
This PR adds support to format using buildifier when starlark files are saved.
This uses the Bazel extension's buildifier support which enables`Format Document` command to work on Starlark files.
=> feat(devcontainer): Enable buildifier formatting on save

apps/ohhighwaysigns/oh_highway_signs.star
App was not getting the chosen location correctly. There was no crash, just displayed the default message.
Now properly decodes the JSON string and defaults to camera `101` if nothing found.
=> OH Highway Signs: Fix Location Decoding

apps/apps.go, apps/strava/strava.go, apps/strava/strava.star
Hello!
The applet in this PR implements a simple display for summary stats from [Strava](https://strava.com) using their API. You log in using OAuth and can display data from your runs, rides or swims either all-time or your YTD stats only. Currently the application is under my user, but happy to transfer this if the Tidbyt team feels that would be easier to maintain! Only the client id and secret would need to be replaced.
Here are a few more images from the Pixlet environment showing other options and the relating config:
- Runs: https://i.imgur.com/h5dX9Ox.png
- Swims: https://i.imgur.com/LSlfvgI.png (apologies to swimmers for the lack of personal data here!)
- YTD Rides: https://i.imgur.com/3wAlDkP.png
Happy to hear/incorporate any feedback you may have.
=> Add Strava applet

apps/warframecycles/warframe_cycles.star
Times could be a minute or a bit more off due to caching with TTL=60, so I'm offsetting the time by -1 minutes if fetched from cache.
=> Add cache offset for times

apps/spotthestation/spotthestation.star
Added on icon animation
Fixed timezone bug -- since XML feed doesn't provide timezone information, the calculations to determine first future date could by off by a timezone offset.
Since I can calculate how long the current XML is valid, I can optimize the TTL for the cached XML
=> Icon animation, fix timezone offset error, set ttl to optimum value

apps/tempest/tempest.star
The API returns air_temperature always as a whole number so don't force it to be a float with a 0 decimal part
=> drop decimal of temperature as it is always 0

apps/strava/strava.star
According to the RFC, OAuth 2.0 scopes should be space-delimited,
but Strava expects them to be comma-delimited.
This actually worked in the dev environment because Pixlet dev tools
mistakenly send scopes as comma-delimited. However, the Tidbyt
smartphone app sends scopes as space-delimited.
Work around this for Strava by having a single "scope" with a comma in
it.
=> strava: Fix scopes to work with Tidbyt app

apps/analogtime/analog_time.star
Was using `render.Plot` and it wanted data before width and height arguments when I updated pixlet files, so simply named each argument to prevent breakage. I don't know if this is live on your end yet, but if it is then this app may not be actually plotting.
Without this fix though `pixlet render` does not work locally for me. It has to do with tidbyt/pixlet#221 (this format makes a ton more sense though).
=> Analog Time: fixed potential argument bug in `render.Plot`

apps/strava/strava.star
Apologies - this should have been in https://github.com/tidbyt/community/pull/283. The timestamp range on previous activities is wrong in the last PR, this corrects it.
=> Strava: bug fix for new screen, correct date range for previous activities

apps/worldclock/world_clock.star
This is meant to address the label bug in the world clock app, which is live in the app right now and is [affecting end users](https://discord.com/channels/928484660785336380/931545988756283412/955854041269809202).
I'm unable to test this locally as Pixlet doesn't allow me to preview the location schema output. So fingers crossed!
=> Fix world clock labels

apps/apps.go, apps/usyieldcurve/us_yield_curve.star, apps/usyieldcurve/usyieldcurve.go
Hi Tidbyt team,
This PR adds a new applet to the library that displays the daily yield curve, similar to how one might monitor it in a Bloomberg terminal. The data is retrieved without authentication from treasury.gov via XML and no configuration is required. The white line shown represents the latest yields, while the fading blue lines represent historical curves going back to the beginning of the year - I find this display offers a very intuitive read on the direction of the curve's movement and helps me visually assess whether it is steepening/flattening.
Finally, I include the current value of the 10-year note and the spread between the 10-year and the 2-year; two closely monitored data points by investors since they represent the base cost of long term debt financing (e.g. mortgages) …
=> New Applet: US Yield Curve

apps/strava/strava.star
Due to the popularity of this app, we're currently exceeding Strava's default allotted API usage limits. This PR does a few things to help mitigate this:
- Reduce API calls on summary screens by caching data for all periods and sports when we first receive it (no downside here, we should've done this anyway)
- Reduce API calls on monthly screen by combining the previous and current month activities into a single query (the downside here is the max number of activities - if the athlete has completed >200 activities in the last two months, their monthly chart will be inaccurate)
- Save all activities when querying for the monthly screen rather than just the sport selected - also no downside here, something I should have been doing but this only affects cases where people choose the monthly …
=> Strava: Extend cache life, reduce number of API calls

apps/randomslackmoji/README.md, apps/randomslackmoji/random_slackmoji.star
- Previously this app assumed all images were square and set the size to 32 x 32. They were not in fact all square but we didn't have a way of knowing the true dimensions of the images. But, now [Pixlet supports resizing one side of an image and maintaining aspect ratio](https://github.com/tidbyt/pixlet/pull/224). With this PR we no longer set the width of images instead relying on pixlet to maintain aspect ratio by only setting the height.
- Replaces our pseudo random number generator with the new official random number module.
=> Slackmoji: maintain image aspect ratio + use random module

apps/nycbus/nyc_bus.star
Hey all! As someone who lives much closer to a bus stop than a subway, I really love @samandmoore's NYC Bus app. One of the stops I've configured has buses from an express SBS line, so the name of the bus overflows within the box:
Technically I still know which bus it is, but figured this could be cleaned up a bit! With Sam's blessing, this enhancement will split any bus codes exceeding 4 characters into two parts and alternate between them:
You may also notice that I took a moment to realign the text and fonts to match the official Tidbyt Subway & Ferry apps and make the whole experience feel a bit more cohesive. If you compare side-by-side (and when they are alternating on the device), there are a few minor differences that this PR resolves: border position (-1px) and color, marquee …
=> NYC Bus: Formatting suggestions

apps/vergetaglines/verge_taglines.star
This change moves the http call inside the cache miss (caught in https://github.com/tidbyt/community/pull/374). This also fixes a typo and makes the cache key a bit more descriptive.
=> Optimization: Verge Taglines app

apps/warframecycles/warframe_cycles.star
Warframe is played on four different platforms, PC, Xbox, PS4, and Switch, so I've added a schema to allow connections to the API for each of these. Even though currently the times are synchronized across all four platforms, they may not be in the future.
I also had the wrong cache keys before, including one that probably wasn't unique ("earth"). In fixing those, I discovered that if they had ever hit, it would have broken the rest of the app because of what I was storing in those keys, so I've had to separate each of the 4 original keys into 2 keys each, for a total of 8 per platform, times 4 total platforms, means 36 for the whole app.
=> Adding platforms and fixing caching

apps/finevent/finevent.star
Currently, if someone is not limiting the displayed events to those occurring within 90 minutes we might be showing events that are far in the future. This PR includes a small improvement - when an event is not within 24 hours we display the date instead:
Upcoming events that occur the following day will still show the time:
Thanks to David from the discord community for the suggestion!
=> Finevent: minor enhancement

apps/apps.go, apps/traffic/traffic.go, apps/traffic/traffic.star
This PR revives the functionality of a previously high-usage app - @LukiLeu's live traffic. As you'll recall, the cost of serving Google's Maps API proved to be unsustainable and it was subsequently removed from the app library after receiving hundreds of installs. This alternative app provides a familiar display with two new sources of data, and users will need to bring their own API keys in order to keep license usage low.
- **MapQuest**: provides real time directions for driving, cycling and walking, influenced by their traffic data
- **OpenRouteService**: provides "ideal" travel times that do not reflect traffic for a broader array of travel modes: e-bikes, wheelchairs, freight and hiking.
**Also, since I'm unable to test the location selection tool from my local Pixlet emulator, I …
=> New App: Traffic

apps/usyieldcurve/us_yield_curve.star, apps/usyieldcurve/usyieldcurve.go
Hi!
Following some community feedback here, this simple PR adds a zoomed-in view of the US yield curve for short, medium and long term bonds, following industry conventions for ranges. Each display shows the spread across visible maturities only, as well as the current yield of the longest maturity bond in view.
This requires no additional data, and the default display is unchanged; the "All" view will still show the 10 year yield and 10Y-2Y spread since this is the most popular indicator.
Thanks to golashes from Discord for the suggestion!
=> US Yield Curve: Add zoom feature

apps/espnnews/espn_news.star, apps/espnnews/espnnews.go
So vertical scroll was initially having issues with cutting off headlines, so made it so a max of 12 lines can be seen in each headline and all headline has an equal width of space, so there will be a variable width between headlines some large, but figure it is better to be consistent if anything.
Also removed the fail and will return an error message if data cannot be obtained
=> ESPN News: Fixed Vertical scroll

apps/redditrplace/reddit_r_place.star
changing the image hold time from 1500 to 1 to allow for correct app switching - the it appears as if the `animation.AnimatedPositioned` `hold`  (and likely but not tested `duration`) property overrides the app switch delay
=> fixing image hold - lasts longer than app switch

apps/sportsscores/sports_scores.star
When a game that has not started and one that has end up on the same frame the ongoing games time gets cutoff. Switched the order of the time remaining and current period for ongoing games to prevent this
=> Sports Scores: NHL format bug fix

apps/traffic/traffic.star
Small bugfix here: the reverse geo functions for MQ and ORS are both expecting numeric types for the coordinates, and I believe we're getting strings back from `schema.Location` - this applies float conversion to resolve. 
Please let me know if I'm mistaken about the cause of the error!
=> Traffic: Fix reverse geo search

apps/mbta/mbta.star
This hasn't been launched for too long! So sorry @marcusb for the back and fourth and the really long delay on this one. The underlying issue is that options are passed into config as a json blob, which made the stop parameter work in preview but not when a stop was selected. More info can be found [here](https://github.com/tidbyt/pixlet/blob/main/docs/schema/schema.md#locationbased), which I don't believe existed when this app was submitted.
- [mbta: Fix mbta stop options.](https://github.com/tidbyt/community/commit/f51757ea5df051137517539e083b63db8784456d)
- This commit resolves an issue where the stop is returned as an option. There are two issues on the Tidbyt side that we need to address. One is that we need to support location options in the dev tools. The second is it's really …
=> mbta: Fix mbta stop options.

apps/fivesomewhere/five_somewhere.star
I hadn't cleaned up any underscores, so did that. Also removed some linked entries in the timezone database because, for example, "Dublin, Europe" works instead of "Eire". Did some special-casing for items in camel-case and that are shortened in the timezone database name, like "Navajo" -> "Navajo Nation".
=> fix some display issues and special cases

apps/verticalmessage/vertical_message.star
message now starts at the bottom and scrolls up
=> Vertical Message: fix marquee offset

apps/cryptotracker/crypto_tracker.star
Percent truncation is currently applied based on the price truncation toggle. This fixes to use the percent truncation toggle.
=> Decouple price/percent truncation

apps/charlestownferry/charlestownferry.star
- Fixed issue where "No ferries" text was not fully visible
- Improved layout of ferries list and added in time-till label
=> Layout improvements for CharlestownFerry app

apps/usgsearthquakes/usgs_earthquakes.star
While the default options worked well for California, they probably aren't very good for other parts of the world. Changed the default radius to unlimited which should always result in a good preview. I likely could have set the minimum magnitude to 4, but we'll use 3 to be extra sure we'll get at least one result.
=> USGS Earthquakes: Update defaults for better previews.

apps/traffic/traffic.go, apps/traffic/traffic.star
@LukiLeu noticed yesterday that MapQuest's traffic coverage is very limited to select metro regions in the US, and suggested we try the Bing API instead. Fortunately, their API 1. also allows free requests up to a limit, 2. has dramatically better international traffic coverage, and 3. supports public transit routes!
This PR implements Bing as a third data source for both route times and reverse geocoding, as well as the addition of public transit as shown above.
For reference, a full table of the API's geographic coverage of routing and traffic information can be found here: https://docs.microsoft.com/en-us/bingmaps/coverage/geographic-coverage
Similar to MapQuest and ORS, Tidbyt users will need to visit https://www.bingmapsportal.com/ in order to register a new app and generate an API …
=> Traffic: Add Bing Maps API

apps/goodservice/goodservice.star
Right now, "Myrtle–Wyckoff Avs" show up as "Wyckoff Avs", which is weird.
This change will have "Myrtle–Wyckoff Av" show up as "Myrtle Av" and "Bedford–Nostrand Avs" as "Bedford Av."
=> goodservice: Display first street for station names that use a combination of 2

apps/baywheels/bay_wheels.star, apps/sfnextmuni/sf_next_muni.star
With this PR, we cache the timestamp at which the data was fetched along with the data itself, and use that and the "seconds" in the GTFS prediction to calculate the actual current minutes, rather than just echoing the minutes as returned by GTFS.
This PR also adds a setting to hide predictions nearer than a minimum number of minutes.
=> SF Next Muni app: more accurate predictions

go.mod, go.sum
This commit manually bumps the pixlet version.
=> fix(deps): update module tidbyt.dev/pixlet to v0.17.9

apps/apps.go
This app is failing HTTP reqeusts when getting stations. The issue is, because the request is in get_schema, our server fails to load the app all together. The Tidbyt team needs to figure out why this request is failing on our end since it does work with pixlet and we need to figure out a better way to ensure our server can startup when an app fails to create schema. I'm disabling the app for now so that we can get the rest of the apps out 😿
=> indegostations: Temporarily disable app.

apps/sportsscores/sports_scores.star
Had `config.str` instead of `config.bool`. This should fix the paginated speed on the app now from going crazy
=> Sports Scores: Fixed frame speed factor issue

apps/strava/strava.star
The monthly progress plot has had a small bug for a while - the current month line doesn't update for the current date due to an off-by-one error in the function that generates the frames.
This plot error isn't obvious if you're adding activities regularly but becomes increasingly noticeable if you take a break. As an extreme example, if your last activity was June 1st but today is the 15th, the plot should show a flat orange line out to the middle of the screen, but currently only shows a dot at the beginning.
=> Strava: Monthly progress plot bug

apps/worldclock/world_clock.star
This adds new functionality to the world clock app that allows support for up to four timezones onscreen at once.
I couldn't see any way to dynamically adjust the schema based on user inputs, so the third and fourth clocks will show up in the mobile app interface even when the user has chosen to display only two or three clocks.
See below for examples.
Four timezones:
Three (the default):
Two:
=> Support up to four timezones in world clock

apps/sunrisesunset/sunrise_sunset.star
Negative padding for time component is currently shaving of 1 pixel for single digit hours in AM/PM format:
After this change:
=> sunrisesunset: stop first digit from being cut off

apps/shopifychart/shopify_chart.star
Found an issue where I had a Shopify line item that did not have a SKU.
Also took the chance to make sure the compare was case insensitive and removed any trailing whitespace.
@matslina
=> Fixed bug with some Shopify Line Items that do not contain a SKU

apps/todoist/todoist.star
I like this app, but I would prefer an option to not have the app show when I have no tasks that I need to worry about.
I'd like to add a config toggle which would allow the app to not render when the number of tasks fetched is zero.
It defaults to the current behavior so that only users who change this config would opt-in to not rendering the app in this scenario.
=> Todoist config to allow hiding when no tasks

apps/strava/strava.star
When we get an HTTP 429 (rate limit exceeded), back off for a few
seconds before trying again.
=> strava: Don't hammer the API when we get HTTP 429

apps/fullybinarytime/fullybinarytime.star
Noticed that the time was off by some exact number of hours, which made me think there was a timezone issue.
Using America/New_York, it's currently 14:26. It now says "on early sub 1101" which is correct. With the old code, it said "on late sub 0010" which is after 6pm. That's four hours later, which makes sense since NY is currently on GMT-4.
In Europe/London, it's currently 19:32. It now says "on late sub 1000", which is just after 19:30. It used to say "on late sub 0010", which is around 18:30. That also makes sense since with daylight savings London is currently on GMT+1
=> Fix timezone issue

apps/fairfaxconnector/fairfax_connector.star
- Display routes in the color specified in the API per-route
- Display arrival as minutes remaining instead of just a timestamp
- ~Change config from a plain text input to a dropdown populated with every bus stop~
- ~@matslina Let me know what you think about this, since we were discussing it. I'm not sure this is the best solution tbh, and it comes with quite a performance hit - on my machine this takes about 5 seconds to "spin up" and make all the requests before they're in the cache. If you don't think it's a good idea, I'll just remove this change and leave the other two in.~
- I'm getting rid of this as it's causing errors in the test suite
<hr/>
=> Add better time, colors, config to ffxconnector

apps/life/life.star
Following up on comment in [pull request](https://github.com/tidbyt/community/pull/560) about performance, and using [profiler](https://github.com/tidbyt/pixlet/pull/353).
Speed up achieved by:
1. Reusing two Box objects rather than creating one per pixel per frame
1. iterating over changed cells in each generation rather than all cells in the board
1. keeping track of how many neighbours a cell has, so we don't have to keep recomputing it
1. caching results, particularly for later frames where there are just oscillators for many frames
Benchmark results using my laptop below, comparing the existing and updated versions of the app.
Starlark profiler shows 92% less time spent executing the Starlark code:
```shell
$ for i in {0..9}; do ./pixlet profile --pprof="top 1" …
```
=> Speed up life by 10x

apps/ethstaker/ethstaker.star
I was reading through a couple other pull requests just to get a feel for the code, and noticed this comment:
https://github.com/tidbyt/community/pull/595#discussion_r949560795
Given the cache is global and the statuses that I'm storing are going to be specific to the validators which you're showing in the app, we need a unique key
=> Ethstaker caching fix

apps/vergetaglines/verge_taglines.star
This updates the Verge Taglines with the following:
- Use the new `align` feature of Marquee and remove the custom text centering
- Add an offset configuration so scrolling brings the text into view on render to address a readability issue
Here is an example of how a tagline from today, which is not scrollable, fits before and after the change.
Before
After
=> Update: Verge Taglines to use new marquee centering and add scroll offset

.github/workflows/cla.yaml
This commit adds an additional renovate bot. At some point, renovate
changed from an account to an app on GitHub which broke this
integration.
=> cla: Add alternate renovate.

apps/sportsscores/sports_scores.star, apps/sportsscores/sportsscores.go
All scores still reset at 11am ET, except Soccer - EPL gets reset at 11am London time
=> Sports Scores: Adjust time scores get reset (account for EPL)

apps/vergetaglines/ReadMe.md, apps/vergetaglines/verge_taglines.star
This is an update to my existing Verge Taglines app.
[The Verge](https://www.theverge.com) released a new site design today - the bane of any web scraper. Gone are the top banner images, but they [still have a tagline at the top](https://twitter.com/reckless/status/1569890682889973761?s=20&t=18rJN0IPqwgYrsDoFH4z2w), so this update adds their new logo as a placeholder and applies a new selector to capture the tagline, as it did before.
Since no header image is available, the background will random rotate between five of the prominent colors on the Verge's main page.
=> Update Verge Taglines to account for site redesign

apps/goodservice/goodservice.star
Small fix to skip rendering when there's no data from the selected station.
=> Goodservice: Skip rendering when there's no data

apps/sfnextmuni/sf_next_muni.star
New Features:
* Route Filter: Filter predictions to only one route for a given stop
* Prediction Formats: Two Line w/Destination only shows predictions for the next two lines, two times, w/ destination. Larger Font
* Prediction Formats: Two Line w/4 Times only shows predictions for the next two lines, 4 times, no destination. Larger Font
Enhancements:
* Added line colours for E and F lines
* Display route letter for F and S lines as black to provide better contrast
* Improved KT route tag override to properly show K or T depending on which stop and to match Muni signage
* Better handling of default config values when pixlet commands are used as get_schema is not currently called then
=> SF NextMuni Updates

apps/sportsscores/sports_scores.star
Sometimes the game status of inning, quarter, period can be cutoff, so have added a toggle to hide the ordinal ending of the game status
=> Sports Scores: Add toggle to hide ordinal numbers

apps/nhllive/nhl_live.star
Next game time shouldn't be cached for Preview Game States. With timezone differences, users would most likely received the wrong upcoming game time. This update forces Preview Game States to calculate game time right before render, using already existing game data.
=> fix issue with NHL Live app caching preview next game time

apps/londonbusstop/london_bus_stop.star, apps/tube/tube.star, apps/tubestatus/tube_status.star
1. Make sure app keys are encrypted using names of the .star files (e.g. "london_bus_stop") rather than the folder ("londonbusstop")
2. Truncate latitude and longitudes to three decimal places for better caching when calling the API.
=> Fixes for London apps

apps/borisbikes/boris_bikes.star, apps/busytube/busy_tube.star, apps/londonbusstop/london_bus_stop.star, apps/tube/tube.star, apps/tubestatus/tube_status.star
1. Don't send API requests for locations outside the UK because the API always returns a failure.
2. Show error messages rather fail() the app. It's a better user experience.
3. Also cache failed API responses so we don't keep spamming TfL's service that they kindly provide for free.
=> Handle API failures better

apps/sportsscores/sports_scores.star
Just shortened the text on a toggle schema so the toggle actually shows up. Would have though the text would have wrapped? is there a way to enduce that such as \\ or \, or what is the character limit?
=> Sports Scores: Shorten text on a toggle schema

apps/nhllive/nhl_live.star
Used a cached variable in a wrong spot causing the game info update line to remain stuck on "Next Game ..." until the cache for that had expired. Also was caching the opponent of the selected team ... which would force that be the retrieved "next game" for that team - possibly missing an earlier game for them.
=> FIX: NHL Live - fix cache issues

apps/mbtanewtrains/mbta_new_trains.star
The API response changed, adding in an `isNewTrain` attribute.  This PR updates the applet to respect that flag.
=> [fix] Mbtanewtrains over counting

apps/severewxalertsusa/severewxalertsusa.star
@aschechter88 this PR should resolve #646 to at least make alerts readable until you can find some time to play around with the display more if desired. As per that discussion, I simply swapped `render.Sequence` for `render.Animation`. the `delay` parameter may need to be modified to show alerts quick enough, but I did not test that. Again if you want to change the icon for hide app when no alerts, you may also consider that.
=> SevereWxAlertsUSA: fix overlapping alerts

apps/officestatus/office_status.star
This commit adds a default client ID so the tests for this repo will pass. There was a shuffle in how apps were created in this repo that lead to this app not having tests running on it.
=> office status: Add default client ID.

apps/netatmo/netatmo.star
Originally used º instead of °, fixing to use °
=> Fix netatmo to use degree symbol

apps/textbyt/textbyt.star
Update the height of the Marquee widget to account for the fixed header line.
Fixes #698
=> fix: Fix (lack of) scrolling for textbyt messages

apps/pagerduty/pagerduty.star
Due to some recent changes to my company's PagerDuty account, I noticed that the app was crashing with insufficient permissions:
```json
{
"error": {
"message": "Required abilities are unavailable",
"code": 2014,
"errors": [
"The teams account ability is required to filter by teams."
],
"missing_abilities": "teams"
}
}
```
PagerDuty offers an abilities endpoint to test whether features are available or not. I've implemented that to restore the app to working order for users on the Professional plan which does not include Teams support in the API.
=> Only support teams on accounts with the teams ability

apps/mbta/mbta.star
It'd be useful for me to have an option to only show trains/buses arriving above a certain amount of time, since I'm a 5 minute walk away from my stop. Thought others might want this option too.
=> Added minimum arrival time to MBTA

apps/desknametag/desk_name_tag.star
The app does not display field descriptions. The initial version of this applet assumed these values would be shown to help users. I've updated the applet to add help text to the color field names so users know they need to enter a full hex code.
=> feat: Add help text to color field names

apps/apps.go, apps/apps_test.go
Seems like there's been a bunch of issues recently where changes aren't being reflected in apps.go, then people get confused. Or they accidentally removed existing apps when making their change due to sync issues.
Existing tests check that everything in apps.go is backed up by code in the repo.
This goes the other way and checks that what's in the repo is registered.
You can still quickly unregister existing apps if they start misbehaving. Just have to add the directory name to "exclusions" list and the test will ignore it.
=> Test that all apps are registered

apps/apps.go, apps/shopifyorders/shopify_orders.star, apps/shopifyorders/shopifyorders.go, apps/shopifysales/shopify_sales.star, apps/shopifysales/shopifysales.go
Shopify Orders and Shopify Sales tidbyt apps managed by the [Shopify Counter app](https://apps.shopify.com/counter).
Shopify Orders: displays the count of orders on your store within the time period
Shopify Sales: displays the money sales value generated by your store within the time period
Note: you'll need a demo `counterId` param to test, ping privately for this.
=> Add shopify orders and shopify sales apps

apps/apps.go, apps/ordertrends/order_trends.star, apps/ordertrends/ordertrends.go, apps/salestrends/sales_trends.star, apps/salestrends/salestrends.go, apps/shopifyneworder/shopify_new_order.star, apps/shopifyneworder/shopifyneworder.go
Adds 3 new apps:
Shopify New Orders: show details for recent orders on your store
Shopify Order Trends: Show daily, weekly, etc order count data
Shopify Sales Trends: Show daily, weekly, etc sales data
=> Add shopify new orders, order trends, sales trends apps

apps/nightscout/nightscout.star
This cache is used only when Nightscout returns an error. The cache ensures a blood sugar value is shown (and displayed as stale) for up to 30 minutes if NS is temporarily unavailable. It does not affect live glucose values if they are available as this app never displays cached data unless there is a NS error.
=> Change NS Error Cache to 30 mins

apps/todoist/todoist.star
Per Todoist, v1 of the API is deprecated and has been removed on November 30th. As a result, this app is currently broken until this pull request is merged. Sorry I missed the deprecation announcement!
We didn't use any features which changed between v1 and v2, so this change simply adjusts our URL to point to their new v2 endpoint. Tested locally and works with this change. Thanks!
See https://developer.todoist.com/rest/v1/#overview:
DEPRECATED: This version of the REST API (v1) is deprecated and will be removed on Nov 30. Please refer to the v2 documentation.
=> [break fix] Upgrade Todoist from Rest API v1 to v2.

apps/shopifymemories/shopify_memories.star, apps/shopifyorders/shopify_orders.star, apps/shopifysales/shopify_sales.star
- Use a marquee for custom date text in shopify orders and sales apps
- fix animation timing in memories app
=> Fix text overflow in shopify orders and sales apps. Fix animation timing in memories app

apps/daystoxmas/days_to_xmas.star
First, I love this applet and I loved discovering it in the tidbyt app! I am hoping seasonal things like this continue to make appearances.
There is a small bug in this applet where it uses a UTC date comparison instead of the local timezone. That means that in the evening west coast time today 2022-12-11, it shows "13 days until Christmas" instead of "14 days until Christmas".
The issue is that 
```
xmas_timestamp = time.time(year = today.year + 1, month = 12, day = 25).in_location(timezone)
```
Should be
```
xmas_timestamp = time.time(year = today.year + 1, month = 12, day = 25, location = timezone)
```
The former initializes a UTC 2022-12-25 and then translates it into PST - which is 2022-12-24. The latter creates a reference to 2022-12-25 in PST.
I also cleaned up some readability …
=> Fix timezone off-by-one error in Is It Xmas applet

apps/nightscout/nightscout.star
This PR removes the `trend` variable from Nightscout. This variable was not used during rendering, and not all CGM sources seem to set this variable so it could cause errors during render.
For example, here's an entry from my Nightscout `entries.json`:
```json
{
"_id": "639cc6bde169cee86173fe72",
"device": "xDrip-DexcomG5",
"date": 1671218875550,
"dateString": "2022-12-16T19:27:55.550Z",
"sgv": 139,
"delta": -2,
"direction": "Flat",
"type": "sgv",
"filtered": 0,
"unfiltered": 0,
"rssi": 100,
"noise": 1,
"sysTime": "2022-12-16T19:27:55.550Z",
"utcOffset": -360,
"mills": 1671218875550
},
```
=> fix(nightscout): Remove trend variable

apps/apps.go, apps/idlegardener/idle_gardener.star, apps/idlegardener/idlegardener.go
I often times download and delete Idle games on my phone. I like the idea of a game where I dont have to do anything, but it will play itself. I think the idea of having a tree chopping (or planting) simulator is a really fun concept for an Idle Game.
Thus, enter Idle Gardener! This is a set and forget type of Idle game. You can watch the counter go up every time the app is re-run and the trees animate in from a `chopped` state, to `grown`. The counter will grow as you clear out the trees, and they grow back just in time for you to cut them down again!
**Note:** I considered that some users might not like the idea of deforestation, therefore I added a `Green Mode` that will plant the trees instead - same animation, just makes you feel like you are making a difference! They share the same …
=> New App: Idle Gardener

apps/vergetaglines/verge_taglines.star
This fixes the currently broken Verge Taglines app with the updated path to the tagline from the embedded data block on the page.
=> fix(verge-taglines): Update mapping of tagline from data block

apps/nightscout/nightscout.star
Fix vertical bars where hour crosses day.
Vertical hour bar was not passing test to render when hour was midnight GMT
=> Nightscout: Fix vertical bars where hour crosses day

apps/effheadlines/effheadlines.star, apps/fuzzyclock/fuzzy_clock.star, apps/ifparank/ifparank.star, apps/manifest/testdata/source.star, apps/metar/metar.star, apps/mvv/mvv.star, apps/outlookcalendar/outlook_calendar.star, apps/sbbtimetable/sbb_timetable.star, apps/stepcounter/stepcounter.star, apps/tempest/tempest.star, apps/testpatterns/test_patterns.star, apps/theguardiannews/theguardiannews.star
This commit adds a module docstring to the apps that don't have one by copying the information for the go source.
=> Fix module-docstring warnings.

apps/ctaltracker/cta_l_tracker.star, apps/njtransit/nj_transit.star, apps/pathtrainschedule/path_train_schedule.star, apps/traffic/traffic.star, apps/transsee/transsee.star
This warning, in the community repo, mostly complained about "doc strings" having no effect. I moved all doc strings or converted the comment type to satisfy this check. The warning is useful in the general case though, since it identifies unused variables.
=> Fix no-effect warning.

apps/sportsstandings/sports_standings.star
Seems NHL and NFL were having issues getting the correct names for stats to display standings. have changed it to try and get stats by name instead of abbreviations to try and remedy this
=> Sports Standings: Fix standings for sports

apps/nesquotes/nes_quotes.star
The original method was not correct, and the linter complained about result being unused. The issue is, this method is used to create an ID for schema fields. If we change the ID, it will break any existing installations. Therefore, the safest option is to mimic the behavior of the original function. cc @markmcintyre
=> Fix NES Quotes unused variable.

apps/githubrepo/github_repo.star
id for owner/organization should be `organization`, not `owner` this is fixed
=> GitHub Repo: Fix config bug

apps/ethstaker/ethstaker.star
This commit resolves our last lint waring for status being undefined. I am not sure the intent here, and looking through the rest of the source code was no help. I presume this method already was erroring given this was not defined. My fix satisfies the linter but it likely does not resolve the logic error in this mehthod. cc @ColinCampbell
=> Fix ethstaker lint warning.

apps/analogclock/analog_clock.star, apps/analogtime/analog_time.star, apps/bigclock/big_clock.star, apps/binaryclock/binary_clock.star, apps/clockbyhenry/clock_by_henry.star, apps/colorfulclock/colorful_clock.star, apps/countupclock/countupclock.star, apps/datetimeclock/date_time_clock.star, apps/fullybinarytime/fullybinarytime.star, apps/hexcolorclock/hex_color_clock.star, apps/nixelclock/nixel_clock.star, apps/worldclock/world_clock.star
By default, the Tidbyt will display stale images it recieves near idefinitely if it cannot get an update from our backend. In almost all cases, this is the desired behavior. The weather isn't going to change much within a 10 minute time frame. However, a 10 minute stale clock would be incredibly frustrating. We implemented a mitigation for our clock some time ago that sets the max age to two minutes for the clock, ensuring the most stale clock image the device would show would be no greater then 2 minutes. However, we never rolled out that change to all clocks. This commit updates all clocks in the community repo to not be displayed if they are stale.
=> fix: Set max_age for clocks.

apps/borisbikes/boris_bikes.star, apps/busytube/busy_tube.star, apps/londonbusstop/london_bus_stop.star, apps/nationalrail/national_rail.star, apps/solarelevation/solar_elevation.star, apps/tube/tube.star, apps/tubestatus/tube_status.star
Transport apps are also time sensitive, and solar elevation is really a clock.
=> Add max_age

apps/apps.go, apps/mastodonfollows/mastodon_follows.star, apps/mastodonfollows/mastodonfollows.go
This PR adds a Mastodon Follows app similar to my Twitter Follows app. I took a slightly different approach to this than #877, with these three goals in mind:
1.  I wanted to add the follower count of any username on an instance, not just my own
2.  I did not want to have to login to get the follower count
3.  I did not want to hardcode a list of instances into the app, so this searches [instances.social](https://instances.social) instead.
You can get your own free token for the search call [here](https://instances.social/api/token) if you'd prefer.
=> New App: Mastodon Follows

apps/apps.go, apps/discordmembers/discordmembers.go, apps/discordmembers/discordmembers.star
Adds a new app that displays the members count of a Discord Server. This is done by fetching an invite URL that contains an approximate members count. Therefore, a valid invite ID must be supplied as an input variable.
The app's layout and structure are inspired by the `twitterfollows` example.
**Example Render:**
=> New App: Discord Members Count

apps/apps.go, apps/stripesales/README.md, apps/stripesales/stripe_sales.star, apps/stripesales/stripesales.go
This app does one simple thing: displays a user's Stripe sales made so far today. 
It only requires a user to provide a Stripe API Key, and all of the requests to the Stripe API are made directly, not through any external proxy.
=> New App: Stripe Sales

apps/newapps/new_apps.star
Accidentally was setting the cache key of new apps differently than the key I was trying to get, so it was constantly hitting the tidbyt api. This app will not display anything until new apps are merged. It seemed to be working yesterday, so we'll see if this works. I think the logic on line 37 should be right (we want it to update a current list if it just got a new old list).
=> New Apps: Fixed Cache key

apps/tetrisclock/tetris_clock.star
The location is provided as a JSON encoded string, which is not intuitive and I totally missed it during review. This change updates the default location to be a string and decodes it inside the app so the passed location from our backend will parse. cc @MarkGamed7794
=> tetris-clock: Fixup location.

apps/meh/manifest.yaml, apps/meh/meh.star
Displays the daily deal from meh.com -- the image, text, and price. Defaults to "No Deal." Uses a 10-miute cache for deal and image because sometimes they have multiple deals in a day.
I've attached a render of the "No Deal" -- when it can't contact meh.com, for whatever reason.
=> feat: add Meh app for meh.com

.github/workflows/pull-request.yml
I'm working to add target determination so we only build what's changed on pull requests. In order to do that, I need to know what references are available on PRs. It's especially confusing because I need to know what the build system sees on forks. This commit adds a reference printing so I can see what PRs have available today.
=> build: Add git reference printing.

.github/workflows/pull-request.yml
This commit adds printenv so that I can see what environment variables exist in the builds we have today.
=> build: Add printenv.

.github/scripts/check-apps.sh, .github/scripts/determine-targets.sh, .github/workflows/pull-request.yml
This change updates the build to only build the differential to the merge commit. This means we no longer have to test all apps 🎉 . I'm going to follow up with more changes so that we no longer are using the merge commit and instead are using the HEAD of the branch, which would allow us to only build what's being modified in the pull request.
- [build: Utilize targets in pixlet check.](https://github.com/tidbyt/community/pull/1085/commits/f8f286b7dd6fd7cd373c63ed33dabf9c0e938401) 
[f8f286b](https://github.com/tidbyt/community/pull/1085/commits/f8f286b7dd6fd7cd373c63ed33dabf9c0e938401)
- This commit uses the output from the target determination step in pixlet check.
- [Move to shell scripts](https://github.com/tidbyt/community/pull/1085/commits/6e85f1986c7a124c7e158fbe20e84bca235a4406)
=> build: Use target determination

.github/scripts/check-apps.sh, .github/scripts/determine-targets.sh, .github/workflows/pull-request.yml
This change updates our build to use the head ref as defined in the [checkout plugin docs](https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit) instead of a merge commit. Traditionally, building off of the merge commit is safer given it's also testing the integration of the main branch and your feature branch. However, in the community repo, each app is self-contained and all we really care about is the changes being introduced since the branch was created.
- [build: Use pull request head on checkout.](https://github.com/tidbyt/community/pull/1096/commits/74b19e1632dcd6ae2f522260f0647a685446c812) 
- This commit updates the checkout action to use the head of the pull request as the reference to checkout instead of the merge commit.
- [build: Update …
=> build: Use pull request head on checkout.

.github/scripts/determine-targets.sh, .github/workflows/pull-request.yml, apps/zapier/zapier.star
This change does two things. It goes back to using the merge commit and it uses the merge-base of the GitHub base SHA and the head sha of the branch being committed. I tried to do this before using the references passed into the build, but they broke on PRs from forks.
=> build: Use merge base

apps/adelaidemetro/adelaide_metro.star
Fixed bug 2 - showed no time when its the last service for the day/for a while
I caused this one after the last update...oops!
=> Bug fix: Adelaide Metro

apps/tetrisclock/tetris_clock.star
Tetris clock on my tidbyt is like 10 minutes behind so added max_age to see if that helps.
cc @MarkGamed7794 for review.
I know it's likely not your app that is causing this issue and it may be something on Tidbyt's side, but this should at least allow it to not show times where it is like 10 to 20 minutes off hopefully. I know not everyone is having this issue though, but I would like to keep this on my tidbyt so want to try this first.  
I've seen it be on time in the preview and then when I resave configs it corrects itself, but then it starts to drift and becomes 10 minutes off, I am keeping an eye on it to at least see if the slippage gets larger. But because the preview in the app is right, but what's being displayed is wrong I'm not sure what's up. 
Info on `max_age` can be found …
=> Tetris Clock: Add max age

apps/customstatus/custom_status.star, apps/customstatus/manifest.yaml
This is a branch off of the original Office Status app. It is intended for users who want to display a custom status during specific times of the week. Users can set up multiple iterations of this applet and utilize the Tidbyt app's scheduling functionality to determine when this status should display. I removed the integrations with Webex and Outlook to reduce the burden on the user.
I don't like creating a separate applet with similar functionality as Office Status. But, adding a weekly schedule option for custom statuses in the core application would make the applet too cumbersome for users.
=> New App: Custom Status

apps/testcricket/test_cricket.star
Version 1.2
- Added Team Innings to scoreboard and changed font
- Show 'need' not 'trail' when in the 4th innings
- Only use mobileName if it exists
=> Update: Test Cricket

apps/airthings/airthings.star
Adds an option to the 'Airthings' applet to only display "not normal" values (values that are in the yellow or red range).
Example:
=> Airthings: add option 'onlyDisplayNotNormal'

apps/nightscout/manifest.yaml, apps/nightscout/nightscout.star
Moved Sample Data out of global to avoid caching and expiration of default data display
=> Nightscout: Moved Sample Data out of global (v2.2.4)

apps/noaabuoy/noaa_buoy.star
if a buoy goes down it will return a 404.  Instead of displaying an error, use old data and keep track of how long we are using it. Once it's 30 minutes stale(or 3 data fetch cycles) invalidate and display the error. 
Change error to indicate its a buoy.
Change default buoy to one that is not down at the moment.
=> noaa_buoy : indicate stale cache and invalidate after 3 cycles

.github/scripts/determine-targets.sh, .github/workflows/main.yml
Right now, the main branch builds everything. This change updates the main branch to only build the difference between the last successful build and the current build. While not overly useful at the moment, we will be able to deploy only what changed once this repo can deploy itself.
- [feat: Only build what changed.](https://github.com/tidbyt/community/pull/1194/commits/b75db8a51c3012e9b665628003ad81f448f6936c) 
- This commit updates the main branch to only build what has changed.
=> build: Only build changes on main branch

apps/pgatour/pga_tour.star
Fixed bug - when there are multiple events on (opposite field events, like this week) the app is showing both leaderboards under the 1 tournament heading. The toggle was only really changing the heading
Should be fixed up now so you can see one or the other, not both
=> Fix: PGA Tour

apps/surfforecast/surf_forecast.star
Sometimes these bar height functions return floats rather than ints if the values returned from the surfline API are just right. Floats are not a valid type for Box heights.
I've also put off rounding until the final step of the calculation to allow the bar heights be more precise.
=> Fix Surf Forecast bar height bug

apps/airbnbcalendar/airbnb_calendar.star, apps/airbnbcalendar/manifest.yaml
This app is a calendar that displays the coming week of reservations for multiple Airbnb listings, as pulled from Airbnb's iCal export URLs. It looks like this[^1]:
iCal URLs that do not start with `https://www.airbnb.com/calendar/ical/` are rejected to prevent abuse, and successfully fetched results are cached for five minutes. Please message me if you'd like to test using my private Airbnb iCal URLs.
This was a fun thing to build, thanks to the Tidbyt team for an enjoyable platform! Here are a few ideas that would help make building things like this easier:
- I'd love a way of selecting a timezone without using the `Location` widget, since I don't need lat/lon or other user information. Is the list of timezones available in the runtime somewhere, to populate a `Dropdown`?
- It would be …
=> New app: Airbnb Calendar

apps/githubactivity/github_activity.star, apps/githubrepo/github_repo.star
After displaying these for a bit on my tidbyt, relized these should have the full animation flag otherwise you'll never see some of the content
=> GitHub Activity and GitHub Repo: Add show_full_animation

apps/nationalrail/national_rail.star
Responding to bug pointed out by users here, sorry it's taken a while: https://discuss.tidbyt.com/t/national-rail/4485/2
The thread was helpful for pointing out that the issue occurs only when setting a filter. I found I got an error whenever a filter station was selected.
That's because I was putting a whole JSON object into the filter condition, rather than just the relevant CRS value. Tested this locally and no longer get an error when setting a filter.
=> Fix nationalrail app

apps/flightsnearby/flights_nearby.star
This isn't my app, but I wanted to contribute a couple changes:
1. Option to hide app when no flights nearby
2. Display optional extra information on flight (bearing, speed, heading)
3. Filter for flights at least 1000 feet off the ground
4. Add additional option of 20km radius
=> Hide when no flights, optional extra information on nearest flight

apps/splat3challenges/splat3_challenges.star
- Moves the stage images 1 pixel down in order to be in line with the other Splatoon app.
- Changes the main-body scroll animation to end after the text goes offscreen, instead of when the text hits the header a second time.
- Adds two more config options: one for image brightness when text is overlaid, the other for scroll speed.
Sorry for the PR so soon. I figured I should make the app more accessible and clean.
=> Fix scroll animation, add more config options

apps/outlookcalendar/outlook_calendar.star
Removed erroneous inclusion of the uri_redirect parameter in the Refresh token endpoint call
=> Outlookcal uri bugfix

apps/sffogtoday/manifest.yaml, apps/sffogtoday/sf_fog_today.star
This adds a new app which display the current satellite (from GOES-16) fog cover image from @loganwilliams's [fog.today](https://fog.today/) website, cropped into main part of San Francisco. Image data is cached to be requested at most once per minute.
In the future it might be nice to transform the image a bit (increase contrast so the areas with no fog cover are black pixels) or maybe even use a GOES image directly with a map border overlay pixel-optimized for the Tidbyt, but both of these require image manipulation that is currently impossible with the APIs available from Pixlet.
=> New app: SF Fog Today

apps/faadelays/faa_delays.star, apps/faadelays/manifest.yaml
This adds a new app that displays information about airport delays for US airports supplied by the FAA. The information comes from an XML API feed on the [National Airspace System Status](https://nasstatus.faa.gov/) website.
This app depends on a bugfix in Pixlet I've submitted here: https://github.com/tidbyt/pixlet/pull/824
(screenshot is sample data, not real)
=> New app: FAA airport delays

apps/btchalving/btchalving.star
Fixed the calculation in BtcHalving. Apparently a width of 0 is resulting in a width of 100%. I also changed the colors a bit.
=> BtcHalving: fix calculation

apps/milbscores/milb_scores.star
Minor change to use Hawaii timezone to check what day it is. 
This means that the day's scores will remain on display until 6am Eastern the next day, before changing to that day's schedule
Good for those MiLB fans coming home late and wanting to see the day's scores :)
=> Update: MiLB Scores

apps/aflscores/afl_scores.star, apps/phaseofmoon/phase_of_moon.star
Added additional feature to display the active time (clock) as this is helpful in my case. I have been using this app as the only app on my Tidbyt at nighttime instead of the default built-in, nighttime display of the time. Great initial app by @alan-fleming!! 🎉 Happy to share and opening a PR as I think this feature may also be helpful to others as well.
=> Added: optional clock

apps/steamtopsellers/README.md, apps/steamtopsellers/manifest.yaml, apps/steamtopsellers/steam_top_sellers.star
Draft proposal for a "Steam Top Sellers" app. This simply renders a random selection from Steam's Top Sellers list, including the game name, price, (optional) discount and an image.
There are some notes for improvements and quality-of-life enhancements. Specifically, the caching and animation timing may use further refinement. The animation quality/length was also significantly reduced to keep the rendered file size under the required limit.
There are no configuration parameters required at this point.
Open to suggestions/feedback. Also including a preview image:
=> Draft Steam Top Sellers app

apps/afl/afl.star
@henrygg98 tried to add a new feature in #2375 to show standings in the AFL app, but the slow render times wouldn't allow his changes to go through. I think I have made sufficient changes to it to allow for it to render in under a second in most cases and added the option he wanted as well. Tagging app author @andymcrae in case he wants to review as well.
=> [AFL] updates to reduce render time, add standings option

apps/chesscomelo/chesscom_elo.star
Fixes #2430
`pixlet render chesscom_elo.star username=nzdominic` if you need a test case that was failing before (but please excuse my poor chess skills 😆)
=> chesscomelo: add support for unrated stats

apps/ukpolling/uk_polling.star
- The BBC moved the data table widget off the main page
- Probably because it's a bit slow
- Updating the URL makes nice graph work again
=> fix UK polling URL

apps/playdatesales/manifest.yaml, apps/playdatesales/playdate_sales.star
This app tracks any sales going on  in the Playdate Catalog. If there are no sales, then this app does not appear.
=> New App: Playdate Sales

apps/houseofcommons/house_of_commons.star
If the government count is exactly divisible by 13 then there isn't a remainder. So we shouldn't add a remainder column to the picture. But currently, we are trying to add a very tall column (probably due to division by almost zero), which looks weird and means the seat counts don't get shown
=> Fix infinite height

apps/weightgurus/weight_gurus.star
The big fix here is only requesting from the Weight Gurus API the data in the period we want to display.
- Less data over the wire is always good
- Over time you can reach a limit on records returned, it's oldest first, and there's no pagination, so your Tidbyt is just stuck showing stale data forever.
Also includes better messaging on api errors, some TODO removal and cleanup, and removal of config options that don't work given the above API limitations.
=> Weightgurus api call improvements

apps/berlintransit/berlin_transit.star, apps/berlintransit/manifest.yaml
This commit adds the Berlin Transit app to the repository. The app provides information about upcoming train and bus departures for a given Berlin station. It uses VBB APIs to get real time departure info for Berlin transit. It's modeled off of several other transit-related apps, though primarily tube.star. It displays the station configured to track departures for at the top, and a rotating set of departures from that station below, with each departure containing the line name (e.g. U2, S41), destination of the departure, and the time until departure.
There are several parameters users can configure to change the behavior of the app. First and foremost is the station parameter, where users can look up stations via location services. This parameter . Second is a departure time offset, …
=> feat: Add Berlin Transit app

apps/goodservice/goodservice.star, apps/goodservice/manifest.yaml
* Rebrand app to The Weekendest, to align with the newly launched iOS app. I kept the id and file names the same so that existing users won't be affected. Let me know if that's something I should change too.
* Fix name of Mets–Willets Point: It used to just say "Mets", now it'll say "Willets Pt" instead.
=> Goodservice: Rebranding to The Weekendest, and fix destination name for Mets–Willets Point

apps/gradientclock2/gradientclock2.star
This fixes an incorrect timezone handling on this app, as reported by user candido in the forums: https://discuss.tidbyt.com/t/the-time-on-the-new-clock-apps-are-two-hours-wrong/6543
@tpatel12 we need your approval here.
=> [FIX] Gradient Clock: incorrect timezone handling

apps/azhighwaysigns/az_highway_signs.star, apps/azhighwaysigns/manifest.yaml
This app allows a user to select any of the AZ Highway Message signs and display it's current message on their Tidbyt!
The AZ Highway Message signs are a collection of electronic roadway message boards to alert drivers to changing traffic info, detours, distance to key landmarks, etc - sometimes, they're even just fun messages!
Examples of real signs:
This app uses the AZ 511 API (https://www.az511.com/help/endpoint/messagesigns) to pull the current message from any sign, then formats it for display on a Tidbyt. If there are multiple messages (some signs rotate through a few) active for a sign, a random one will be displayed.
=> AZ Highway Signs

apps/goodservice/goodservice.star
* New `scheduled_routes` field is more relevant for the schema, since `routes` is completely dynamic, and can lead to no routes being listed due to service changes.
=> The Weekendest: Update station schema to use scheduled routes instead of routes

apps/hassentitylist/hassentitylist.star
The app seems to have been designed for number entities which don't have units. When used with sensors, it's useful to also include units of measurement (e.g. "80 %" instead of just "80").
=> hassentitylist: render units for entities which have them

apps/nhdesdata/nh_des_data.star
This is a change to the `nhdesdata` app to prevent the likelihood of seeing the "No data" text show up.
Instead of trying to pull the most recent reading from the past 3 hours, the app will now look at the past 24 hours.
Additionally, the date and time of the last available reading will be shown so that the user is aware of exactly when the temperature was recorded.
=> nhdesdata: Update to show the most recent reading in the past 24 hours

apps/nsbyt/nsbyt.star
If maintenance is active for longer than a few days, some trains may not include a message. This fixes a crash of the app.
=> NSByt Fix if no message is supplied

apps/olympicmedals/olympicmedals.star
A typo meant that the default value of `frames` was set improperly. I changed the default values of it and `delay` to be a bit more reasonable.
=> olympicmedals: Fix default speed

apps/fpltracker/fpl_tracker.star, apps/fpltracker/manifest.yaml
This PR introduces a new applet, FPL Tracker. This applet lets you track a Fantasy Premier League (English Premier League's official fantasy game) team and displays stats such as the points scored this gameweek and the overall rank.
It uses the official FPL API and requires no authentication other than providing the team id to track.
=> New App: FPL Tracker

apps/hasssolar/README.md, apps/hasssolar/hass_solar.star
This PR adds support for widget mode by only rendering the main frame.
It also includes a small formatting bugfix where values between 9950 and 9999 W were be displayed as "10.0 kW" which is too long for the main frame - those are now shown as "10 kW".
=> hass-solar: only show main frame in widget mode

apps/fpltracker/fpl_tracker.star
Fixed bugs with the previous week rank logic
1. Corrected rank change direction being reversed
2. Corrected prev_rank being a list of 1 value and not an int
=> FPL Tracker:  Bug Fixes

apps/launchcountdown/launchcountdown.star
The description from the service generally includes the UTC time of launch. 
Since I've calculated the launch in the local time, I replace the UTC display with the local time display.
There was a bug as a fix I put in to replace a recurring oddball character (\u202f) with an empty string should have replaced it with a single space.
=> Fix description bug

apps/melbournetrains/melbourne_trains.star
- Fix `typo` in schema menu description: `Chose` to `Choose`
- Updated `changelog` history to keep track of changes
- Increased the size of the `platform number` box to make more use of screen realestate
=> Update: Melbourne Trains - Minor Updates

apps/nightscout/manifest.yaml, apps/nightscout/nightscout.star
Add color selectors and color display code for in-range, high, low, urgent high, urgent low readings. Also for Clock, IOB, COB display 
Moved IOB and COB below reading when no graph is shown 
Cleaned up spacing in no-graph mode
Cleaned up spacing for stale display with IOB or COB below reading
=> NightScout - Add Color Selectors

apps/pagerduty/pagerduty.star
Hey @matslina, had a couple of folks on Discord ask about the PagerDuty app being broken. 
Testing with a free trial locally, I found that the `/abilities/teams` endpoint is returning 204 without a body, leading to a JSON parsing failure. This change ensures that a body will always be passed.
=> [pagerduty] handle more body-less responses

apps/stripespotlight/README.md, apps/stripespotlight/manifest.yaml, apps/stripespotlight/stripe-spotlight.star
The Stripe Spotlight applet allows a user to display the `gross volume` (the sum of all successful payments) for their store. 
To do so, users will need to input their Stripe API key under `Stripe API Key`. They can then set a custom store name under `Store Name` (it defaults to Stripe), and choose a date range to display: `Today`, the `Last 7 days`, `Last 4 weeks`, `Last 3 months`, `Last 12 months`, `Month to date`, `Quarter to date`, `Year to date`, or `All time` (these are the same date ranges that are available in the Stripe dashboard).
=> New App: Stripe Spotlight

apps/goodservice/goodservice.star
Allows you to set a comma-separated list of lines (e.g. `"A,C"`) to filter to show instead of all the lines of the station.
=> The Weekendest: Add option to only show certain lines

apps/splatoon3schedule/splatoon3schedule.star
The data format has been changed for Final Fest. Update the app to handle this new format.
=> splatoon3schedule: support Tricolor Turf War for Final Fest

apps/londonbusstop/london_bus_stop.star
Looks like TfL have changed their response format. It used to provide details of the stop in the children attribute. Now, the relevant fields have been moved up to top-level fields, which is simpler.
Also being more tolerant of unknown bus stop letter codes.
Tested around my house (handful of top-level stops) and around King's Cross (many stops, nested within a hub).
Fixes https://github.com/tidbyt/community/issues/2656
=> Fix London bus stop app

apps/dayssince/README.md, apps/dayssince/days_since.star, apps/dayssince/manifest.yaml
I saw the Accident Free Days app when setting up my new Tidbyt Gen 2 and thought that it would be more versatile if the 'accident' could be custom text too.
It also dawned on me that it would probably be an easy enough first Tidbyt app, something I've wanted to try my hand at ever since receiving my Gen 1 a few years ago.
So this app lets the user set a custom date and custom text, so they can let the world know how many days have elapsed since the thing happened.
=> New App: Days Since

apps/homefiniti/homefiniti.star, apps/homefiniti/manifest.yaml
This app shows live visitor stats for certain websites hosted by our company for our clients (homebuilders in the US). The user will get an easy-to-type API key from their admin dashboard. Shown below is sample output with and without an API key.
=> New App: Homefiniti

apps/spanishwotd/manifest.yaml, apps/spanishwotd/spanish_wotd.star
Updates the Spanish Word of the Day app to use the Word of the Day from [SpanishDict.com]( https://www.spanishdict.com/wordoftheday) rather than using the English word of the day from Merriam Webster and showing a translation of it.  Also makes it so it displays: `[Spanish word]: [English Translation]` rather than `[English word]: [Spanish Translation]`
I love @logancornelius 's Spanish WotD app! But, fetching an English word of the day, and then showing it's Spanish translation doesn't really feel like a true "Spanish Word of the Day" app. The English words from Merriam Webster also tended to be quite obscure, so not great for learning useful Spanish vocabulary.
This MR takes a bit of a different approach to getting a Spanish WotD. Instead of fetching an English word and then translating …
=> Update Spanish WotD app to use SpanishDict

apps/fbw-flight-stats/flybywire_flights.star, apps/fbw-flight-stats/manifest.yaml
An app that tracks the number of flights using the [FlyByWire Simulations](https://flybywiresim.com/) systems, with a nice animation that works well for the Normal rate, but even for the Turbo speed. For Normal speed it will float the FlyByWire Logo and the count from the left, and exit the frame to the left. For other speeds, it will float in, then stay and be replaced with the next app. 
FlyByWire Simulations is a non-profit group of volunteers who build FOSS (GPL licensed) add-ons and infrastructure for Microsoft Flight Simulator 2020 (and 2024 in the future). Our current mainline add-on, called A32NX, is a representation of the A320Neo for MSFS and we are actively working on a representation of the A380 as well. All of this is done out of love and passion for the Flight Simulator …
=> Adding FlyByWire Statistics app

apps/hassgraph/hass_graph.star
App HASS Graph:
This PR makes the App show timestamps in local time instead of UTC
@vincentezw : Hope you like the idea.
=> App hassgraph: show lowest/highest in local time

apps/vipabfahrten/vipabfahrten.star
App ViP Abfahrten:
It now does not calculate the remaining time in minutes anymore and instead uses the time string given by the service operator.
=> App ViP Abfahrten: Use timestring given by operator

apps/gw2_fractals/gw2_fractals.star, apps/gw2_fractals/manifest.yaml
This adds a new app to preview the [daily Fractal of the Mists](https://wiki.guildwars2.com/wiki/Fractals_of_the_Mists#Daily_Fractals) from the game Guild Wars 2.
There are a collection of different dungeons in Guild Wars 2 called "fractals." Difficulty (known as "scale") ranges from 1 to 100, and is broken up into four difficulty tiers (Tier 1 = scale 1-25, Tier 2 = scale 26-50, etc). A specific scale is always the same dungeon (eg, scale 1 is always the "Volcanic" fractal). Within a specific tier, some fractals only show up once, and others show up twice (eg, in Tier 4, Swampland is both scale 77 and 89).
Every day, 3 fractals are the "daily fractals" and have increased rewards. You can complete this at any scale that features this fractal (eg, "Daily Tier 4 Swampland" can be earned by …
=> New App: Guild Wars 2 Fractals

apps/pdp11/manifest.yaml, apps/pdp11/pdp11.star
The PDP11/70 was a groundbreaking 16-bit computer from the early 1970s. I was inspired by the PiDP11 kit which I built and have on my desk. The visualization of the LEDs is random and this is just a toy which no function other than looking at a simulacrum of a computer older than me (and most everyone else in the community).
The PDP11 ran at universities, banks, insurance companies, etc. 16-bit addressing was groundbreaking as was the instruction set. However it's still over 30k less powerful than a Raspberry Pi 4. 
https://en.wikipedia.org/wiki/PDP-11
I am not associated with the PiDP11, but it was a fun thing to build - https://obsolescence.wixsite.com/obsolescence/pidp-11.
Note: I've only tried it on a v2 Tidbyt as that's all I own!
=> Add PDP11/70 blinkenlights visualizer

apps/sbbtimetable/sbb_timetable.star
This pull request optimizes the spacing of the SBB App, mainly for the Tidbyt Gen 2.
In short: 
- The char ':' in the time is drawn manually. This removes unnecessary empty spaces around that char.
- The box on the left side is reduced to 7px instead of 8px. The text was, anyway, only 7px wide.
- The spacing between the box and the time, as well as the time and the destination, is increased to two pixels.
Before:
After:
=> Improve spacing sbb app

apps/bigbrothernews/big_brother_news.star, apps/bigbrothernews/manifest.yaml
Updated the [Big Blagger](https://bigblagger.co.uk) logo and colour scheme. Also removed references to bbspy (previous news source) from the manifest. 👁️
=> New logo and colour scheme for the new Big Brother season

apps/overwatch_meta/overwatch_meta.star
- The name of the character is spelled "Reinhardt" and not "Reinhard", source: https://www.overbuff.com/heroes/reinhardt
- The full name of "Reinhardt" extends beyond the screen, so I needed to correct a dictionary that maps the full name of "Reinhardt", to the nickname "Rein".
=> Bug-Fix: Overwatch Meta App - Fixed Spelling for Reinhardt

apps/hasssolar/README.md, apps/hasssolar/hass_solar.star
This allows rendering the app from within Home Assistant without using the Home Assistant REST API.
=> HASS Solar: allow specifying raw values instead of entity IDs

apps/hasssolar/hass_solar.star
This is to avoid cases where the app could display "-0%"
=> Ensure energy and percentages are always >= 0

apps/us_electoral_forecast/us_electoral_forecast.star
Fixes swapped Harris/Trump labels on us_electoral_forecast.
Before:
After:
=> Fix incorrect label on us_electoral_forecast

apps/moretransit/moretransit.star
the moretransit app has a min minutes config property to show trains only that are >= min_minutes away. However, the app currently uses the hardcoded value of 10. 
This fix replaces it with the min_minutes config property
=> bug fix to moretransit app's min minutes feature

apps/homefiniti/homefiniti.star
This allows a user to optionally set a custom logo. If none is specified it displays the default logo.
=> Homefiniti app - allow custom logos

apps/wowcharacterstats/wowcharacterstats.star
Per [this post](https://us.forums.blizzard.com/en/blizzard/t/upcoming-changes-to-battlenet%E2%80%99s-api-gateway/51561), Blizzard is no longer accepting auth tokens via query params, they must be passed in through headers.
=> [WoWCharacterStats] Use headers for auth to Blizzard APIs

apps/splatoon3schedule/splatoon3schedule.star
Turns out they updated the data model for Tricolor Turf War yet again. Update the app to handle this but, if `.data.currentFest.timetable` is ever not null again, make use of that instead. (Hopefully its data model hasn't changed as well.)
=> splatoon3schedule: fix Tricolor Turf War again

apps/customquotes/custom_quotes.star, apps/thingswifesays/things_wife_says.star
Instead of displaying url to a sample google sheet, explaining the type of google sheet that's needed. Easier for users to understand.
=> Simplify app description to explain what kind of google sheet it accepts

apps/skybyt/manifest.yaml, apps/skybyt/skybyt.star
This PR adds an app to track the number of followers for a given account on [Bluesky](https://bsky.app). I used @drudge's Mastodon Follows App as a base and modified it to pull from Bluesky's APIs instead. Since the getProfile endpoint is public, no login credentials are needed.
=> New App: Skybyt

apps/airbnbcalendar/airbnb_calendar.star
I'm not sure what happened, either Airbnb's ical format changing or Starlark's regular expression matching changing, but sometime in the last month or so blocked Airbnb dates started being displayed as normal reservations due to a string mismatch caused by an extra carriage return. This corrects the issue.
Before the change, note how incoming reservation is incorrectly gray for "FUTURE".
After the change, note how incoming reservation is correctly black for "BLOCKED".
=> Add "\r" to string match to prevent false negative

apps/thanksgivingday/thanksgiving_day.star
Also add a 2025 date. App was using the date of the 22nd previously which is incorrect
=> Fix Thanksgiving day math for 2024

apps/indianews/india_news.star
news api is down, replacing with alternate news api which requires slightly different parameters. Added a time function in service of limiting news to between today and yesterday.
=> news api is down, replacing with alternate news api

apps/siderealtimeclock/README.md, apps/siderealtimeclock/manifest.yaml, apps/siderealtimeclock/sidereal_time.star
This is a [Sidereal Time](https://en.wikipedia.org/wiki/Sidereal_time) clock that displays the current local sidereal time (LST) based on the user's location.
There are options to display the time using a blinking colon, to use 24h notation and to also display the local (standard) time along with the sidereal time. All colors are also configurable.
Preview:
=> New app: Sidereal Time

apps/indexticker/index_ticker.star
* Add more indicies 
* Europe 350
* Global 100 
* Global 1200
* NIKKEI -- this was previously commented out as it caused the app to crash (now fixed)
* NZX 50
* Add support for null indicator values 
* Resolves NIKKEI issue
* <details>
<summary>example payload causing havoc before</summary>
<a href="https://query1.finance.yahoo.com/v8/finance/chart/%5En225?metrics=high?&interval=5m&range=1d" target="_blank">https://query1.finance.yahoo.com/v8/finance/chart/%5En225?metrics=high?&interval=5m&range=1d</a> 
</details>
https://github.com/user-attachments/assets/548bc32f-2629-4816-a771-f442ddb8c523
=> fix(indexticker): more indicie and null indicator values support

apps/ctaltracker/cta_l_tracker.star
This PR does two things: 
1. Add two optionally consumed features. Without any change, this app will continue to function as-is for current users
2. Refactor code structure, naming, caching utility and remove unnecessary API token usage* (You can elect to merge without this commit and the features will be added without issue).
I tested this using `pixlet serve`, disabled some caching and my own CTA Arrivals API token. Everything worked on my machine... and I believe it will work on yours. I tested each commit individually incase the refactor was not preferable.
I developed this independently but pivoted to this contribution. I wanted the Tidbyt to help with my commute to work. I live a 7 minute walk from the train station, so knowing the next two trains are arriving now and in 2 minutes …
=> ctaltracker: Add selectable destination and timing offset options

apps/nationalday/manifest.yaml, apps/nationalday/nationalday.star
Show what national day(s) it is according to The National Day Calendar at https://nationaldaycalendar.com
=> new app: National Day Calendar (US)

apps/melbournetrams/melbourne_trams.star
**Description:**
- Add missing stops reported by users:
- Update Route 11 - Add stops: D14, D15, D16, D17, D18
- Update Route 30 - Add stops: D1, D2
- Update Route 48 - Add stops: D14, D15, D16, D17, D18
- Update Route 70 - Add stops: D2, D3, D4, D5, D6, D10, D11, 7A, 7B, 7C, 7D
- Update Route 75 - Add stops: D2, D3, D4, D5, D6
**Note:**
- The above changes have been tested locally and are working as expected 👍🏻
=> Update: Melbourne Trams - Add missing Stops on Routes 11, 30, 48, 70 and 75

apps/permtimeline/manifest.yaml, apps/permtimeline/perm_timeline.star
PERM Timeline offers a comprehensive view of the processing journey for PERM (Program Electronic Review Management) applications, which are part of the U.S. Department of Labor’s process for obtaining permanent labor certifications. These certifications are a critical step for employers sponsoring foreign workers for employment-based green cards.
Discover how many applications were completed today, calculate how long it's been since your submission, and get an estimate of how much time remains before your application is approved. The tool also provides an approximate approval date to help you plan ahead with confidence.
For more information on PERM processing times:
https://flag.dol.gov/processingtimes
Screenshot
=> New app: PERM Timeline

apps/flalighthouses/fla_lighthouses.star
Adjust colors, lighten background image, increase contrast between visited and unvisited lighthouses.
=> Improve Colors

apps/indexticker/index_ticker.star
Any number that's 0.0x%, for example 0.09%, ends up rendering out as `0.9%`. Fix this by using the humanize package's float() to do the hard work for us.
=> indexticker: fix rendering of 0.0x%

apps/anime_next_ep/anime_next_ep.star, apps/anime_next_ep/manifest.yaml
Create a Tidbyt app that shows when the next episode of an anime is airing by leveraging the AniList api
Implementation should follow the anilist usage guidelines
[AniList Rate Limiting](https://docs.anilist.co/guide/rate-limiting)
> The API is currently in a degraded state and is limited to 30 requests per minute. This is a temporary measure until the API is fully restored.
[AniLIst terms of use](https://docs.anilist.co/guide/terms-of-use)
> 1. Free for non-commercial usage. See our [commercial usage](https://docs.anilist.co/guide/terms-of-use#commercial-usage) section for more.
> 2. Using the AniList API as a backup or data storage service is strictly prohibited.
> 3. Hoarding or mass collection of data from the AniList API is strictly prohibited.
> 4. Applications or services must …
=> Initial implementation of anime next ep

apps/anime_next_ep/anime_next_ep.star
original PR https://github.com/tidbyt/community/pull/2935
As suggested by @danielsitnik instead of searching for anime by ID, search by name
Note: [pixlet typeahead](https://github.com/tidbyt/pixlet/blob/c29059778792f1731822098aeb71f9bf5567b38b/src/features/schema/fields/Typeahead.jsx#L42-L54) is slightly broken in that if the result is not a substring of the options, then it won't be shown.
ex. if I search "Solo Leveling" the api will return "Ore dake Level Up na Ken" but there no options are shown because the Autocomplete component from mui filters this out.
I hope this is not the case in the mobile app
=> [animeNextEpisode] Search anime by name instead of ID

apps/nbastats/manifest.yaml, apps/nbastats/nba_stats.star
This app displays the current NBA stat leaders in points per game, rebounds per game, assists per game, blocks per game and steals per game. It scrapes from the NBA league leaders website to retrieve the most up-to-date statistics.
=> New App: NBA Stat Leaders

apps/newsmix/news_mix.star
Per https://github.com/tidbyt/community/pull/2931#issuecomment-2704796981, remove NYT RSS feeds from the app
=> News Mix - Remove NYT RSS feeds

apps/gw2_fractals/gw2_fractals.star
~~I'm not fully sure what changed, but an off-by-one error suddenly started showing up this month in my GW2 Fractals app. This addresses it and brings it in line with the values found in the referenced script [here](https://wiki.guildwars2.com/wiki/Template:Day_of_year_index#Return_values).~~
EDIT: Just kidding, it was a leap year/non-leap year issue. The previous implementation wasn't skipping 59 on non-leap years like expected. I've compared the results of this function with the values from the tab [here](https://wiki.guildwars2.com/wiki/Template:Day_of_year_index#Return_values) for various dates in leap years and non-leap years to confirm it's working.
=> fix: address off-by-one error

apps/pihole/pihole.star
This pull request enhances the Pi-hole app by adding support for HTTPS schema in hostnames. Previously, the app only supported HTTP schema. Backward compatibility is maintained by appending `http://` if no schema is detected in the hostname.
=> Update PiHole to add support for HTTPS schema in hostnames

apps/nycaspstatus/manifest.yaml
This pull request includes a small change to the `apps/nycaspstatus/manifest.yaml` file. The change adds the `fileName` and `packageName` fields to the manifest to provide additional metadata about the NYC ASP Status application.
* [`apps/nycaspstatus/manifest.yaml`](diffhunk://#diff-ed940dad8acaff758ac2cad07400143b096548c7657a3a24a5fbacf652bd50b5R7-R8): Added `fileName` and `packageName` fields to the manifest.
=> fix: clean up nycaspstatus manifest

apps/nycaspstatus/manifest.yaml, apps/nycaspstatus/nyc_asp_status.star
NYC ASP Status app is not rendering on the community hub, nor in the Tidbyt cloud. This is probably caused by a mismatched app id, when I originally uploaded the manifest and .star files.
So, I created a new pixlet app and generated a new encrypted key using its id. Everything should match now.
I updated the manifest to reflect the new id, and updated the .star file with the updated encrypted key.
=> Fix NYC ASP Status App

apps/vergetaglines/verge_taglines.star
This is a bug fix to the Verge taglines app which recently started returning the default text ("THE VERGE") after [The Verge](https://theverge.com) updated their page layout and structure again so that the graphql endpoint previously used was no longer functional.
This changes the app back to a previous implementation method which searches the html content since the tagline is now, once again, present in the base HTML returned.
=> Update verge_taglines to correctly select text after site update

apps/upcoming_events/manifest.yaml, apps/upcoming_events/upcoming_events.star
This app accepts an iCal URL from a public Google Calendar and can display multiple events along with their dates.
I put this together because we had been using multiple tidbyt calendar apps for upcoming events and sometimes forgetting to add them. Now this can pull from our shared events calendar without to worry about adding another calendar app for each upcoming event.
=> Add Upcoming Events app to community apps

apps/thisdayhistory/this_day_history.star
update api to use REST API.  Wikipedia broke their normal feed on March 28 - this bypasses the issue.
=> Fix this_day_in_history (take 2)

apps/mlbstandings/mlb_standings.star
The Oakland A's are now without a city and ESPN updated their abbreviation. Fixed the dictionary to handle it.
=> MLB standings: Update abbreviation for Athletics

apps/pinballmap/pinball_map.star
I am a developer of the API that this app uses. Due to the apparent popularity of it, the endpoint is getting hit over 30k times a day when using a ttl_seconds of 30. This PR is an update to the Pinball Map Tidbyt app that increases the ttl to 10 minutes. This seems like a reasonable amount of time.
I await @scottwainstock 's review.
=> Update pinball_map.star ttl_seconds from 30 to 600

apps/ctaLStatus/README.md, apps/ctaLStatus/ctaLStatus.star, apps/ctaLStatus/manifest.yaml
Hi, I've created an app that reports on the status of the CTA 'L' Routes. These are pulled from the CTA's [status](https://www.transitchicago.com/api/1.0/routes.aspx) and [alerts](https://www.transitchicago.com/api/1.0/alerts.aspx) APIs and supports several customized options including:
- Display the headline or short description of an alert
- Configure the scroll speed
- Display alerts that are presently active
- Display alerts that affect elevators and other accessible paths
- Display alerts that are commonly planned on the CTA (worked, reroutes, etc)
- Display alerts that have began in the last seven days
All calls are cached for 5 mins and this program uses the `http` package to make calls to the CTA APIs. I also have another app that reports on the status of CTA Bus Routes as well. …
=> Add App: CTA 'L' Status

apps/shouldideploytoday/manifest.yaml, apps/shouldideploytoday/shouldideploy.star
After developing this, I realized there is an [existing app](https://github.com/tidbyt/community/blob/main/apps/shouldideploy/manifest.yaml), but I'd still like to add this one. It adds some flair and configurability.
- Location will be based on `schema.Location` rather than input, to ensure it matches what the shouldideploy.today is expecting (has error handling too just in case).
- You can choose:
- symbols: black background with ✅ or ❌
- thumbs: red/green background with 👍 or 👎 
Passes checks:
=> New App: Should I Deploy?

apps/weatherbard/README.md, apps/weatherbard/manifest.yaml, apps/weatherbard/weatherbard.star
This app takes the weather condition from openweatherapp and returns one or poetic lines that describe that condition.  It will randomly choose from many.
=> Weatherbard app

apps/oscarscustard/manifest.yaml, apps/oscarscustard/oscars_custard.star
- Apparently when creating the app, I inadvertently spelled "Oscar's" as "Oscars's". This PR changes it to the correct spelling.
- This PR also fixes an issue where HTML entities aren't converted to their proper characters (e.g. `FUNKEEE… MONKEY` is instead shown as `FUNKEEE&8230 MONKEY`). This app went through many iterations back when the time limit for running apps was stricter; it looks like I had simply missed this.
=> Oscar's Custard: Correct spelling, fix HTML parsing

apps/oscarscustard/oscars_custard.star
This PR adds some flavor hints to the Oscar's Custard app, so that (for example) `BLUE MOON` will show in a pale cyan, `BADGER CLAW` will show in red and white, and a few other flavors will receive appropriate colors.
=> Oscar's Custard: Add some flavor hints

apps/bbcsounds/README.md, apps/bbcsounds/bbc_sounds.star, apps/bbcsounds/manifest.yaml
This adds a new app to show what's currently playing on [BBC Sounds](https://www.bbc.co.uk/sounds/stations) radio stations on Tidbyt
It's based on my other Tidbyt apps for [WQXR](https://github.com/tidbyt/community/tree/main/apps/wqxr), [WNYC](https://github.com/tidbyt/community/tree/main/apps/wnyc), and [All Classical Radio](https://github.com/tidbyt/community/tree/main/apps/kqac).
| Current Track                                                                                                         | Programme                                                                                                               |
| --------------------------------------------------------------------------------------------------------------------- | …
=> Add BBC Sounds app

apps/goodservice/manifest.yaml
Follow-up to #3111, I forgot to update the manifest.yaml, which is where the renaming should actually happen.
=> The Weekendest: Update manifest for renaming to Subway Now
